package KTCosNMS;


/**
* KTCosNMS/enAlarmState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022년 10월 19일 수요일 오후 6시 39분 28초 KST
*/

public class enAlarmState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static KTCosNMS.enAlarmState[] __array = new KTCosNMS.enAlarmState [__size];

  public static final int _ALMSTS_Recovery = 0;
  public static final KTCosNMS.enAlarmState ALMSTS_Recovery = new KTCosNMS.enAlarmState(_ALMSTS_Recovery);
  public static final int _ALMSTS_Occurrence = 1;
  public static final KTCosNMS.enAlarmState ALMSTS_Occurrence = new KTCosNMS.enAlarmState(_ALMSTS_Occurrence);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.enAlarmState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected enAlarmState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class enAlarmState
