package KTCosNMS;

/**
* KTCosNMS/enAlarmSeverityHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public final class enAlarmSeverityHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.enAlarmSeverity value = null;

  public enAlarmSeverityHolder ()
  {
  }

  public enAlarmSeverityHolder (KTCosNMS.enAlarmSeverity initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.enAlarmSeverityHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.enAlarmSeverityHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.enAlarmSeverityHelper.type ();
  }

}
