package KTCosNMS;

/**
* KTCosNMS/enAlarmCorrelationFlagHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class enAlarmCorrelationFlagHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.enAlarmCorrelationFlag value = null;

  public enAlarmCorrelationFlagHolder ()
  {
  }

  public enAlarmCorrelationFlagHolder (KTCosNMS.enAlarmCorrelationFlag initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.enAlarmCorrelationFlagHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.enAlarmCorrelationFlagHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.enAlarmCorrelationFlagHelper.type ();
  }

}
