package KTCosNMS;


/**
* KTCosNMS/enAlarmSeverity.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public class enAlarmSeverity implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static KTCosNMS.enAlarmSeverity[] __array = new KTCosNMS.enAlarmSeverity [__size];

  public static final int _ALMSVR_Recovery = 0;
  public static final KTCosNMS.enAlarmSeverity ALMSVR_Recovery = new KTCosNMS.enAlarmSeverity(_ALMSVR_Recovery);
  public static final int _ALMSVR_Minor = 1;
  public static final KTCosNMS.enAlarmSeverity ALMSVR_Minor = new KTCosNMS.enAlarmSeverity(_ALMSVR_Minor);
  public static final int _ALMSVR_Major = 2;
  public static final KTCosNMS.enAlarmSeverity ALMSVR_Major = new KTCosNMS.enAlarmSeverity(_ALMSVR_Major);
  public static final int _ALMSVR_Critical = 3;
  public static final KTCosNMS.enAlarmSeverity ALMSVR_Critical = new KTCosNMS.enAlarmSeverity(_ALMSVR_Critical);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.enAlarmSeverity from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected enAlarmSeverity (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class enAlarmSeverity
