package KTCosNMS;


/**
* KTCosNMS/enAlarmStateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

abstract public class enAlarmStateHelper
{
  private static String  _id = "IDL:KTCosNMS/enAlarmState:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.enAlarmState that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.enAlarmState extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (KTCosNMS.enAlarmStateHelper.id (), "enAlarmState", new String[] { "ALMSTS_Recovery", "ALMSTS_Occurrence"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.enAlarmState read (org.omg.CORBA.portable.InputStream istream)
  {
    return KTCosNMS.enAlarmState.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.enAlarmState value)
  {
    ostream.write_long (value.value ());
  }

}
