package KTCosNMS;


/**
* KTCosNMS/enAlarmCorrelationFlag.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public class enAlarmCorrelationFlag implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static KTCosNMS.enAlarmCorrelationFlag[] __array = new KTCosNMS.enAlarmCorrelationFlag [__size];

  public static final int _ALMCORFLAG_Off = 0;
  public static final KTCosNMS.enAlarmCorrelationFlag ALMCORFLAG_Off = new KTCosNMS.enAlarmCorrelationFlag(_ALMCORFLAG_Off);
  public static final int _ALMCORFLAG_On = 1;
  public static final KTCosNMS.enAlarmCorrelationFlag ALMCORFLAG_On = new KTCosNMS.enAlarmCorrelationFlag(_ALMCORFLAG_On);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.enAlarmCorrelationFlag from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected enAlarmCorrelationFlag (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class enAlarmCorrelationFlag
