package KTCosNMS;


/**
* KTCosNMS/enBoolean.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public class enBoolean implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static KTCosNMS.enBoolean[] __array = new KTCosNMS.enBoolean [__size];

  public static final int _BOOL_False = 0;
  public static final KTCosNMS.enBoolean BOOL_False = new KTCosNMS.enBoolean(_BOOL_False);
  public static final int _BOOL_True = 1;
  public static final KTCosNMS.enBoolean BOOL_True = new KTCosNMS.enBoolean(_BOOL_True);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.enBoolean from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected enBoolean (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class enBoolean
