package KTCosNMS;


/**
* KTCosNMS/enLoadingState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public class enLoadingState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static KTCosNMS.enLoadingState[] __array = new KTCosNMS.enLoadingState [__size];

  public static final int _LOADINGSTS_Start = 0;
  public static final KTCosNMS.enLoadingState LOADINGSTS_Start = new KTCosNMS.enLoadingState(_LOADINGSTS_Start);
  public static final int _LOADINGSTS_End = 1;
  public static final KTCosNMS.enLoadingState LOADINGSTS_End = new KTCosNMS.enLoadingState(_LOADINGSTS_End);
  public static final int _LOADINGSTS_Fail = 2;
  public static final KTCosNMS.enLoadingState LOADINGSTS_Fail = new KTCosNMS.enLoadingState(_LOADINGSTS_Fail);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.enLoadingState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected enLoadingState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class enLoadingState
