package KTCosNMS;

/**
* KTCosNMS/enNetwStateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class enNetwStateHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.enNetwState value = null;

  public enNetwStateHolder ()
  {
  }

  public enNetwStateHolder (KTCosNMS.enNetwState initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.enNetwStateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.enNetwStateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.enNetwStateHelper.type ();
  }

}
