package KTCosNMS;

/**
* KTCosNMS/enNeTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/


//------------------------------------------------------------------------------------------------------
public final class enNeTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.enNeType value = null;

  public enNeTypeHolder ()
  {
  }

  public enNeTypeHolder (KTCosNMS.enNeType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.enNeTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.enNeTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.enNeTypeHelper.type ();
  }

}
