package KTCosNMS;


/**
* KTCosNMS/enResult.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public class enResult implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 10;
  private static KTCosNMS.enResult[] __array = new KTCosNMS.enResult [__size];

  public static final int _RLT_Success = 0;
  public static final KTCosNMS.enResult RLT_Success = new KTCosNMS.enResult(_RLT_Success);
  public static final int _RLT_Comm_Fail = 1;
  public static final KTCosNMS.enResult RLT_Comm_Fail = new KTCosNMS.enResult(_RLT_Comm_Fail);
  public static final int _RLT_Db_Error = 2;
  public static final KTCosNMS.enResult RLT_Db_Error = new KTCosNMS.enResult(_RLT_Db_Error);
  public static final int _RLT_File_Error = 3;
  public static final KTCosNMS.enResult RLT_File_Error = new KTCosNMS.enResult(_RLT_File_Error);
  public static final int _RLT_Auth_Error = 4;
  public static final KTCosNMS.enResult RLT_Auth_Error = new KTCosNMS.enResult(_RLT_Auth_Error);
  public static final int _RLT_NoDef_OpCode = 5;
  public static final KTCosNMS.enResult RLT_NoDef_OpCode = new KTCosNMS.enResult(_RLT_NoDef_OpCode);
  public static final int _RLT_NoDef_TypeCode = 6;
  public static final KTCosNMS.enResult RLT_NoDef_TypeCode = new KTCosNMS.enResult(_RLT_NoDef_TypeCode);
  public static final int _RLT_NoDef_NE = 7;
  public static final KTCosNMS.enResult RLT_NoDef_NE = new KTCosNMS.enResult(_RLT_NoDef_NE);
  public static final int _RLT_NoDef_Seq = 8;
  public static final KTCosNMS.enResult RLT_NoDef_Seq = new KTCosNMS.enResult(_RLT_NoDef_Seq);
  public static final int _RLT_NoDef_Error = 9;
  public static final KTCosNMS.enResult RLT_NoDef_Error = new KTCosNMS.enResult(_RLT_NoDef_Error);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.enResult from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected enResult (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class enResult
