package KTCosNMS;


/**
* KTCosNMS/enServiceGroup.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public class enServiceGroup implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 23;
  private static KTCosNMS.enServiceGroup[] __array = new KTCosNMS.enServiceGroup [__size];

  public static final int _SVCGRP_Sys = 0;
  public static final KTCosNMS.enServiceGroup SVCGRP_Sys = new KTCosNMS.enServiceGroup(_SVCGRP_Sys);
  public static final int _SVCGRP_Loading = 1;
  public static final KTCosNMS.enServiceGroup SVCGRP_Loading = new KTCosNMS.enServiceGroup(_SVCGRP_Loading);
  public static final int _SVCGRP_Ver = 2;
  public static final KTCosNMS.enServiceGroup SVCGRP_Ver = new KTCosNMS.enServiceGroup(_SVCGRP_Ver);
  public static final int _SVCGRP_V52 = 3;
  public static final KTCosNMS.enServiceGroup SVCGRP_V52 = new KTCosNMS.enServiceGroup(_SVCGRP_V52);
  public static final int _SVCGRP_Sli = 4;
  public static final KTCosNMS.enServiceGroup SVCGRP_Sli = new KTCosNMS.enServiceGroup(_SVCGRP_Sli);
  public static final int _SVCGRP_Unit = 5;
  public static final KTCosNMS.enServiceGroup SVCGRP_Unit = new KTCosNMS.enServiceGroup(_SVCGRP_Unit);
  public static final int _SVCGRP_Proc = 6;
  public static final KTCosNMS.enServiceGroup SVCGRP_Proc = new KTCosNMS.enServiceGroup(_SVCGRP_Proc);
  public static final int _SVCGRP_Prc = 7;
  public static final KTCosNMS.enServiceGroup SVCGRP_Prc = new KTCosNMS.enServiceGroup(_SVCGRP_Prc);
  public static final int _SVCGRP_Pwr = 8;
  public static final KTCosNMS.enServiceGroup SVCGRP_Pwr = new KTCosNMS.enServiceGroup(_SVCGRP_Pwr);
  public static final int _SVCGRP_Swt = 9;
  public static final KTCosNMS.enServiceGroup SVCGRP_Swt = new KTCosNMS.enServiceGroup(_SVCGRP_Swt);
  public static final int _SVCGRP_Clk = 10;
  public static final KTCosNMS.enServiceGroup SVCGRP_Clk = new KTCosNMS.enServiceGroup(_SVCGRP_Clk);
  public static final int _SVCGRP_Sig = 11;
  public static final KTCosNMS.enServiceGroup SVCGRP_Sig = new KTCosNMS.enServiceGroup(_SVCGRP_Sig);
  public static final int _SVCGRP_Trk = 12;
  public static final KTCosNMS.enServiceGroup SVCGRP_Trk = new KTCosNMS.enServiceGroup(_SVCGRP_Trk);
  public static final int _SVCGRP_Test = 13;
  public static final KTCosNMS.enServiceGroup SVCGRP_Test = new KTCosNMS.enServiceGroup(_SVCGRP_Test);
  public static final int _SVCGRP_Cbl = 14;
  public static final KTCosNMS.enServiceGroup SVCGRP_Cbl = new KTCosNMS.enServiceGroup(_SVCGRP_Cbl);
  public static final int _SVCGRP_Stm1 = 15;
  public static final KTCosNMS.enServiceGroup SVCGRP_Stm1 = new KTCosNMS.enServiceGroup(_SVCGRP_Stm1);
  public static final int _SVCGRP_Atm = 16;
  public static final KTCosNMS.enServiceGroup SVCGRP_Atm = new KTCosNMS.enServiceGroup(_SVCGRP_Atm);
  public static final int _SVCGRP_Dsl = 17;
  public static final KTCosNMS.enServiceGroup SVCGRP_Dsl = new KTCosNMS.enServiceGroup(_SVCGRP_Dsl);
  public static final int _SVCGRP_Env = 18;
  public static final KTCosNMS.enServiceGroup SVCGRP_Env = new KTCosNMS.enServiceGroup(_SVCGRP_Env);
  public static final int _SVCGRP_EmsRsc = 19;
  public static final KTCosNMS.enServiceGroup SVCGRP_EmsRsc = new KTCosNMS.enServiceGroup(_SVCGRP_EmsRsc);
  public static final int _SVCGRP_EmsNet = 20;
  public static final KTCosNMS.enServiceGroup SVCGRP_EmsNet = new KTCosNMS.enServiceGroup(_SVCGRP_EmsNet);
  public static final int _SVCGRP_EmsRun = 21;
  public static final KTCosNMS.enServiceGroup SVCGRP_EmsRun = new KTCosNMS.enServiceGroup(_SVCGRP_EmsRun);
  public static final int _SVCGRP_EmsSecu = 22;
  public static final KTCosNMS.enServiceGroup SVCGRP_EmsSecu = new KTCosNMS.enServiceGroup(_SVCGRP_EmsSecu);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.enServiceGroup from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected enServiceGroup (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class enServiceGroup
