package KTCosNMS;


/**
* KTCosNMS/enServiceGroupHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

abstract public class enServiceGroupHelper
{
  private static String  _id = "IDL:KTCosNMS/enServiceGroup:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.enServiceGroup that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.enServiceGroup extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (KTCosNMS.enServiceGroupHelper.id (), "enServiceGroup", new String[] { "SVCGRP_Sys", "SVCGRP_Loading", "SVCGRP_Ver", "SVCGRP_V52", "SVCGRP_Sli", "SVCGRP_Unit", "SVCGRP_Proc", "SVCGRP_Prc", "SVCGRP_Pwr", "SVCGRP_Swt", "SVCGRP_Clk", "SVCGRP_Sig", "SVCGRP_Trk", "SVCGRP_Test", "SVCGRP_Cbl", "SVCGRP_Stm1", "SVCGRP_Atm", "SVCGRP_Dsl", "SVCGRP_Env", "SVCGRP_EmsRsc", "SVCGRP_EmsNet", "SVCGRP_EmsRun", "SVCGRP_EmsSecu"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.enServiceGroup read (org.omg.CORBA.portable.InputStream istream)
  {
    return KTCosNMS.enServiceGroup.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.enServiceGroup value)
  {
    ostream.write_long (value.value ());
  }

}
