package KTCosNMS;


/**
* KTCosNMS/enSwitchHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

abstract public class enSwitchHelper
{
  private static String  _id = "IDL:KTCosNMS/enSwitch:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.enSwitch that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.enSwitch extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (KTCosNMS.enSwitchHelper.id (), "enSwitch", new String[] { "SWT_Off", "SWT_On"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.enSwitch read (org.omg.CORBA.portable.InputStream istream)
  {
    return KTCosNMS.enSwitch.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.enSwitch value)
  {
    ostream.write_long (value.value ());
  }

}
