package KTCosNMS;


/**
* KTCosNMS/enSystemState.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public class enSystemState implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static KTCosNMS.enSystemState[] __array = new KTCosNMS.enSystemState [__size];

  public static final int _SYSSTS_Up = 0;
  public static final KTCosNMS.enSystemState SYSSTS_Up = new KTCosNMS.enSystemState(_SYSSTS_Up);
  public static final int _SYSSTS_Down = 1;
  public static final KTCosNMS.enSystemState SYSSTS_Down = new KTCosNMS.enSystemState(_SYSSTS_Down);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.enSystemState from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected enSystemState (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class enSystemState
