package KTCosNMS;

/**
* KTCosNMS/enVendorCodeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class enVendorCodeHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.enVendorCode value = null;

  public enVendorCodeHolder ()
  {
  }

  public enVendorCodeHolder (KTCosNMS.enVendorCode initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.enVendorCodeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.enVendorCodeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.enVendorCodeHelper.type ();
  }

}
