package KTCosNMS;


/**
* KTCosNMS/enVendorCode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public class enVendorCode implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 6;
  private static KTCosNMS.enVendorCode[] __array = new KTCosNMS.enVendorCode [__size];

  public static final int _VENDOR_Rsv = 0;
  public static final KTCosNMS.enVendorCode VENDOR_Rsv = new KTCosNMS.enVendorCode(_VENDOR_Rsv);
  public static final int _VENDOR_Lg = 1;
  public static final KTCosNMS.enVendorCode VENDOR_Lg = new KTCosNMS.enVendorCode(_VENDOR_Lg);
  public static final int _VENDOR_Alcatel = 2;
  public static final KTCosNMS.enVendorCode VENDOR_Alcatel = new KTCosNMS.enVendorCode(_VENDOR_Alcatel);
  public static final int _VENDOR_Samsung = 3;
  public static final KTCosNMS.enVendorCode VENDOR_Samsung = new KTCosNMS.enVendorCode(_VENDOR_Samsung);
  public static final int _VENDOR_Lucent = 4;
  public static final KTCosNMS.enVendorCode VENDOR_Lucent = new KTCosNMS.enVendorCode(_VENDOR_Lucent);
  public static final int _VENDOR_Mercury = 5;
  public static final KTCosNMS.enVendorCode VENDOR_Mercury = new KTCosNMS.enVendorCode(_VENDOR_Mercury);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.enVendorCode from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected enVendorCode (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class enVendorCode
