package KTCosNMS;

/**
* KTCosNMS/EquipInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BcNNMS_AGW.idl
*/

public final class EquipInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.EquipInfo value = null;

  public EquipInfoHolder ()
  {
  }

  public EquipInfoHolder (KTCosNMS.EquipInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.EquipInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.EquipInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.EquipInfoHelper.type ();
  }

}
