package KTCosNMS;


/**
* KTCosNMS/EquipInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BcNNMS_AGW.idl
*/

abstract public class EquipInfoHelper
{
  private static String  _id = "IDL:KTCosNMS/EquipInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.EquipInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.EquipInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [46];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "equipOpCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "equipmentId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "managedIp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "headquarterId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "headquarterName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "nscId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "nscName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "omcId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "omcName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[9] = new org.omg.CORBA.StructMember (
            "officeId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[10] = new org.omg.CORBA.StructMember (
            "officeName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[11] = new org.omg.CORBA.StructMember (
            "rssofficeId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[12] = new org.omg.CORBA.StructMember (
            "rssofficeName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[13] = new org.omg.CORBA.StructMember (
            "equipmentName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[14] = new org.omg.CORBA.StructMember (
            "readCommunity",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[15] = new org.omg.CORBA.StructMember (
            "writeCommunity",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[16] = new org.omg.CORBA.StructMember (
            "emsIp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[17] = new org.omg.CORBA.StructMember (
            "equipUsageCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[18] = new org.omg.CORBA.StructMember (
            "classTypeCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[19] = new org.omg.CORBA.StructMember (
            "vendorCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[20] = new org.omg.CORBA.StructMember (
            "modelName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[21] = new org.omg.CORBA.StructMember (
            "modelNamesCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[22] = new org.omg.CORBA.StructMember (
            "installLocation",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[23] = new org.omg.CORBA.StructMember (
            "addr1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[24] = new org.omg.CORBA.StructMember (
            "degree",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[25] = new org.omg.CORBA.StructMember (
            "snmpversion",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[26] = new org.omg.CORBA.StructMember (
            "spc",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[27] = new org.omg.CORBA.StructMember (
            "spcAlias",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[28] = new org.omg.CORBA.StructMember (
            "equipmentName2",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[29] = new org.omg.CORBA.StructMember (
            "mainClsType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[30] = new org.omg.CORBA.StructMember (
            "subClsType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[31] = new org.omg.CORBA.StructMember (
            "oltNesCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[32] = new org.omg.CORBA.StructMember (
            "oltMstIp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[33] = new org.omg.CORBA.StructMember (
            "oltNeAlias",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[34] = new org.omg.CORBA.StructMember (
            "oltModelName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[35] = new org.omg.CORBA.StructMember (
            "oltNeUsgCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[36] = new org.omg.CORBA.StructMember (
            "rnNesCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[37] = new org.omg.CORBA.StructMember (
            "rnNeAlias",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[38] = new org.omg.CORBA.StructMember (
            "rnModelName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[39] = new org.omg.CORBA.StructMember (
            "rnNeUsgCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[40] = new org.omg.CORBA.StructMember (
            "oltLinkIp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[41] = new org.omg.CORBA.StructMember (
            "slln",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[42] = new org.omg.CORBA.StructMember (
            "ipsecgwIp",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[43] = new org.omg.CORBA.StructMember (
            "trapCommunity",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[44] = new org.omg.CORBA.StructMember (
            "mac",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[45] = new org.omg.CORBA.StructMember (
            "mgid",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (KTCosNMS.EquipInfoHelper.id (), "EquipInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.EquipInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    KTCosNMS.EquipInfo value = new KTCosNMS.EquipInfo ();
    value.equipOpCode = istream.read_string ();
    value.equipmentId = istream.read_string ();
    value.managedIp = istream.read_string ();
    value.headquarterId = istream.read_string ();
    value.headquarterName = istream.read_string ();
    value.nscId = istream.read_string ();
    value.nscName = istream.read_string ();
    value.omcId = istream.read_string ();
    value.omcName = istream.read_string ();
    value.officeId = istream.read_string ();
    value.officeName = istream.read_string ();
    value.rssofficeId = istream.read_string ();
    value.rssofficeName = istream.read_string ();
    value.equipmentName = istream.read_string ();
    value.readCommunity = istream.read_string ();
    value.writeCommunity = istream.read_string ();
    value.emsIp = istream.read_string ();
    value.equipUsageCode = istream.read_string ();
    value.classTypeCode = istream.read_string ();
    value.vendorCode = istream.read_string ();
    value.modelName = istream.read_string ();
    value.modelNamesCode = istream.read_string ();
    value.installLocation = istream.read_string ();
    value.addr1 = istream.read_string ();
    value.degree = istream.read_string ();
    value.snmpversion = istream.read_string ();
    value.spc = istream.read_string ();
    value.spcAlias = istream.read_string ();
    value.equipmentName2 = istream.read_string ();
    value.mainClsType = istream.read_string ();
    value.subClsType = istream.read_string ();
    value.oltNesCode = istream.read_string ();
    value.oltMstIp = istream.read_string ();
    value.oltNeAlias = istream.read_string ();
    value.oltModelName = istream.read_string ();
    value.oltNeUsgCode = istream.read_string ();
    value.rnNesCode = istream.read_string ();
    value.rnNeAlias = istream.read_string ();
    value.rnModelName = istream.read_string ();
    value.rnNeUsgCode = istream.read_string ();
    value.oltLinkIp = istream.read_string ();
    value.slln = istream.read_long ();
    value.ipsecgwIp = istream.read_string ();
    value.trapCommunity = istream.read_string ();
    value.mac = istream.read_string ();
    value.mgid = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.EquipInfo value)
  {
    ostream.write_string (value.equipOpCode);
    ostream.write_string (value.equipmentId);
    ostream.write_string (value.managedIp);
    ostream.write_string (value.headquarterId);
    ostream.write_string (value.headquarterName);
    ostream.write_string (value.nscId);
    ostream.write_string (value.nscName);
    ostream.write_string (value.omcId);
    ostream.write_string (value.omcName);
    ostream.write_string (value.officeId);
    ostream.write_string (value.officeName);
    ostream.write_string (value.rssofficeId);
    ostream.write_string (value.rssofficeName);
    ostream.write_string (value.equipmentName);
    ostream.write_string (value.readCommunity);
    ostream.write_string (value.writeCommunity);
    ostream.write_string (value.emsIp);
    ostream.write_string (value.equipUsageCode);
    ostream.write_string (value.classTypeCode);
    ostream.write_string (value.vendorCode);
    ostream.write_string (value.modelName);
    ostream.write_string (value.modelNamesCode);
    ostream.write_string (value.installLocation);
    ostream.write_string (value.addr1);
    ostream.write_string (value.degree);
    ostream.write_string (value.snmpversion);
    ostream.write_string (value.spc);
    ostream.write_string (value.spcAlias);
    ostream.write_string (value.equipmentName2);
    ostream.write_string (value.mainClsType);
    ostream.write_string (value.subClsType);
    ostream.write_string (value.oltNesCode);
    ostream.write_string (value.oltMstIp);
    ostream.write_string (value.oltNeAlias);
    ostream.write_string (value.oltModelName);
    ostream.write_string (value.oltNeUsgCode);
    ostream.write_string (value.rnNesCode);
    ostream.write_string (value.rnNeAlias);
    ostream.write_string (value.rnModelName);
    ostream.write_string (value.rnNeUsgCode);
    ostream.write_string (value.oltLinkIp);
    ostream.write_long (value.slln);
    ostream.write_string (value.ipsecgwIp);
    ostream.write_string (value.trapCommunity);
    ostream.write_string (value.mac);
    ostream.write_string (value.mgid);
  }

}
