package KTCosNMS;

/**
* KTCosNMS/KtNMSOprExHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class KtNMSOprExHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.KtNMSOprEx value = null;

  public KtNMSOprExHolder ()
  {
  }

  public KtNMSOprExHolder (KTCosNMS.KtNMSOprEx initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.KtNMSOprExHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.KtNMSOprExHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.KtNMSOprExHelper.type ();
  }

}
