package KTCosNMS;


/**
* KTCosNMS/KtNMSOprEx.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class KtNMSOprEx extends org.omg.CORBA.UserException
{
  public String oprName = null;

  // Operation Name
  public String reason = null;

  public KtNMSOprEx ()
  {
    super(KtNMSOprExHelper.id());
  } // ctor

  public KtNMSOprEx (String _oprName, String _reason)
  {
    super(KtNMSOprExHelper.id());
    oprName = _oprName;
    reason = _reason;
  } // ctor


  public KtNMSOprEx (String $reason, String _oprName, String _reason)
  {
    super(KtNMSOprExHelper.id() + "  " + $reason);
    oprName = _oprName;
    reason = _reason;
  } // ctor

} // class KtNMSOprEx
