package KTCosNMS;

/**
* KTCosNMS/KtNMSMsgExHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022년 10월 19일 수요일 오후 6시 39분 28초 KST
*/


//------------------------------------------------------------------------------------------------------
public final class KtNMSMsgExHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.KtNMSMsgEx value = null;

  public KtNMSMsgExHolder ()
  {
  }

  public KtNMSMsgExHolder (KTCosNMS.KtNMSMsgEx initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.KtNMSMsgExHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.KtNMSMsgExHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.KtNMSMsgExHelper.type ();
  }

}
