package KTCosNMS;

import lombok.ToString;

/**
* KTCosNMS/KTSIOMsgHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/
@ToString
public final class KTSIOMsgHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.KTSIOMsg value = null;

  public KTSIOMsgHolder ()
  {
  }

  public KTSIOMsgHolder (KTCosNMS.KTSIOMsg initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.KTSIOMsgHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.KTSIOMsgHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.KTSIOMsgHelper.type ();
  }

}
