package KTCosNMS;


import lombok.ToString;

/**
* KTCosNMS/KTSIOMsg.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/
@ToString
public final class KTSIOMsg implements org.omg.CORBA.portable.IDLEntity
{
  public String sourceSys = null;

  // Originated Source System
  public short neType = (short)0;

  // Type of NE
  public short vendorCode = (short)0;

  // Vendor Code
  public short msgType = (short)0;

  // Message Type
  public int opCode = (int)0;

  // Operation Code
  public int seqNo = (int)0;

  // Sequence No(Requested Unique Id or 0 for Event)
  public short linkedReply = (short)0;

  // Continuous Reply Flag
  public short result = (short)0;

  // Result or Reason Code
  public short tid = (short)0;

  // Target System Id
  public short ssid = (short)0;

  // SubSystem Id
  public short oid = (short)0;

  // SubSystem Object Id
  public short rid = (short)0;

  // System Rack Id
  public short sid = (short)0;

  // System Shelf Id
  public short cid = (short)0;

  // System Circuit Id
  public short lid = (short)0;

  // Line or Port Id
  public org.omg.CORBA.Any msgBody[] = null;

  public KTSIOMsg ()
  {
  } // ctor

  public KTSIOMsg (String _sourceSys, short _neType, short _vendorCode, short _msgType, int _opCode, int _seqNo, short _linkedReply, short _result, short _tid, short _ssid, short _oid, short _rid, short _sid, short _cid, short _lid, org.omg.CORBA.Any[] _msgBody)
  {
    sourceSys = _sourceSys;
    neType = _neType;
    vendorCode = _vendorCode;
    msgType = _msgType;
    opCode = _opCode;
    seqNo = _seqNo;
    linkedReply = _linkedReply;
    result = _result;
    tid = _tid;
    ssid = _ssid;
    oid = _oid;
    rid = _rid;
    sid = _sid;
    cid = _cid;
    lid = _lid;
    msgBody = _msgBody;
  } // ctor

} // class KTSIOMsg
