package KTCosNMS;


import lombok.extern.slf4j.Slf4j;

/**
* KTCosNMS/KTSIOMsgHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/
@Slf4j
abstract public class KTSIOMsgHelper
{
  private static String  _id = "IDL:KTCosNMS/KTSIOMsg:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.KTSIOMsg that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.KTSIOMsg extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [16];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "sourceSys",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[1] = new org.omg.CORBA.StructMember (
            "neType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[2] = new org.omg.CORBA.StructMember (
            "vendorCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[3] = new org.omg.CORBA.StructMember (
            "msgType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "opCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "seqNo",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[6] = new org.omg.CORBA.StructMember (
            "linkedReply",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[7] = new org.omg.CORBA.StructMember (
            "result",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[8] = new org.omg.CORBA.StructMember (
            "tid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[9] = new org.omg.CORBA.StructMember (
            "ssid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[10] = new org.omg.CORBA.StructMember (
            "oid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[11] = new org.omg.CORBA.StructMember (
            "rid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[12] = new org.omg.CORBA.StructMember (
            "sid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[13] = new org.omg.CORBA.StructMember (
            "cid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[14] = new org.omg.CORBA.StructMember (
            "lid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_any);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (KTCosNMS.anySeqHelper.id (), "anySeq", _tcOf_members0);
          _members0[15] = new org.omg.CORBA.StructMember (
            "msgBody",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (KTCosNMS.KTSIOMsgHelper.id (), "KTSIOMsg", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.KTSIOMsg read (org.omg.CORBA.portable.InputStream istream)
  {

    KTCosNMS.KTSIOMsg value = new KTCosNMS.KTSIOMsg ();
    value.sourceSys = istream.read_string ();
    value.neType = istream.read_short ();
    value.vendorCode = istream.read_short ();
    value.msgType = istream.read_short ();
    value.opCode = istream.read_long ();
    value.seqNo = istream.read_long ();
    value.linkedReply = istream.read_short ();
    value.result = istream.read_short ();
    value.tid = istream.read_short ();
    value.ssid = istream.read_short ();
    value.oid = istream.read_short ();
    value.rid = istream.read_short ();
    value.sid = istream.read_short ();
    value.cid = istream.read_short ();
    value.lid = istream.read_short ();
    value.msgBody = KTCosNMS.anySeqHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.KTSIOMsg value)
  {
    ostream.write_string (value.sourceSys);
    ostream.write_short (value.neType);
    ostream.write_short (value.vendorCode);
    ostream.write_short (value.msgType);
    ostream.write_long (value.opCode);
    ostream.write_long (value.seqNo);
    ostream.write_short (value.linkedReply);
    ostream.write_short (value.result);
    ostream.write_short (value.tid);
    ostream.write_short (value.ssid);
    ostream.write_short (value.oid);
    ostream.write_short (value.rid);
    ostream.write_short (value.sid);
    ostream.write_short (value.cid);
    ostream.write_short (value.lid);
    KTCosNMS.anySeqHelper.write (ostream, value.msgBody);
  }

}
