package KTCosNMS;

/**
* KTCosNMS/xAGWHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/


//--------------------------------------------------------------------------------------
public final class xAGWHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGW value = null;

  public xAGWHolder ()
  {
  }

  public xAGWHolder (KTCosNMS.xAGW initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWHelper.type ();
  }

}
