package KTCosNMS;


/**
* KTCosNMS/xAGW.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/


//--------------------------------------------------------------------------------------
public interface xAGW extends xAGWOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

  // Session Management OpCode : 0x50000000 ~ 0x5000000x
  public static final int OPCODE_REQP_Open_Session = (int)(0x50000000);
  public static final int OPCODE_REQP_Close_Session = (int)(0x50000001);
  public static final int OPCODE_REQP_Reopen_Session = (int)(0x50000002);

  // EOCMS Server`? `?`? `?`? AGW `?`?/`?`? `?`?
  public static final int OPCODE_REQP_Add_Managed_Agw = (int)(0x50000010);
  public static final int OPCODE_REQP_Del_Managed_Agw = (int)(0x50000011);
  public static final int OPCODE_REQP_Get_Managed_Agw = (int)(0x50000012);

  // Alarm Request/Response
  public static final int OPCODE_REQP_GetCurrent_Alarm = (int)(0x7A000001);
  public static final int OPCODE_REQP_GetHistory_Alarm = (int)(0x7A000002);

  // POTS Alarm Event
  public static final int OPCODE_NOTI_System_Down = (int)(0x7A000010);
  public static final int OPCODE_NOTI_System_Clock_Inconsistency = (int)(0x7A000011);
  public static final int OPCODE_NOTI_Processor_Signle_Down = (int)(0x7A000012);
  public static final int OPCODE_NOTI_Processor_Dual_Down = (int)(0x7A000013);
  public static final int OPCODE_NOTI_Processor_Abnormal = (int)(0x7A000014);
  public static final int OPCODE_NOTI_Processor_Overload = (int)(0x7A000015);
  public static final int OPCODE_NOTI_Unit_Delete = (int)(0x7A000016);
  public static final int OPCODE_NOTI_Unit_FuncFail = (int)(0x7A000017);
  public static final int OPCODE_NOTI_Unit_PowerFail = (int)(0x7A000018);
  public static final int OPCODE_NOTI_RefClock_CableDelete = (int)(0x7A000040);
  public static final int OPCODE_NOTI_Cable_Delete = (int)(0x7A000041);
  public static final int OPCODE_NOTI_Clock_Fail = (int)(0x7A000042);
  public static final int OPCODE_NOTI_V52_LinkPba_AccessFail = (int)(0x7A000043);
  public static final int OPCODE_NOTI_V52_Interface_OOS = (int)(0x7A000044);
  public static final int OPCODE_NOTI_ATM_PortFault = (int)(0x7A000060);
  public static final int OPCODE_NOTI_ATM_HotLinkFault = (int)(0x7A000061);
  public static final int OPCODE_NOTI_ATM_ULinkFault = (int)(0x7A000062);
  public static final int OPCODE_NOTI_ATM_TrafficCntlFail = (int)(0x7A000063);
  public static final int OPCODE_NOTI_Env_InverterFail = (int)(0x7A000090);
  public static final int OPCODE_NOTI_Env_BatteryFail = (int)(0x7A000091);
  public static final int OPCODE_NOTI_Env_FuseFail = (int)(0x7A000092);
  public static final int OPCODE_NOTI_Env_ACPowerFail = (int)(0x7A000093);
  public static final int OPCODE_NOTI_Env_PowerDistFuseShort = (int)(0x7A000094);
  public static final int OPCODE_NOTI_Env_FireAlarm = (int)(0x7A000095);
  public static final int OPCODE_NOTI_Env_TemperatureAlarm = (int)(0x7A000096);
  public static final int OPCODE_NOTI_Env_HumidityAlarm = (int)(0x7A000097);
  public static final int OPCODE_NOTI_Env_DoorOpenAlarm = (int)(0x7A000098);
  public static final int OPCODE_NOTI_Env_FloodAlarm = (int)(0x7A000099);
  public static final int OPCODE_NOTI_Env_FanAlarm = (int)(0x7A00009A);
  public static final int OPCODE_NOTI_Env_RectifierAlarm = (int)(0x7A00009B);
  public static final int OPCODE_NOTI_Env_BatteryFuseAlarm = (int)(0x7A00009C);

  // DSLAM Alarm
  public static final int OPCODE_NOTI_Dslam_PbaDelete = (int)(0x7A0000B1);
  public static final int OPCODE_NOTI_Dslam_EqptControllerFail = (int)(0x7A0000B2);
  public static final int OPCODE_NOTI_Dslam_EqptInternalHwFail = (int)(0x7A0000B3);
  public static final int OPCODE_NOTI_Dslam_STM1_RS_LOS = (int)(0x7A0000B4);
  public static final int OPCODE_NOTI_Dslam_STM1_MS_LOS = (int)(0x7A0000B5);
  public static final int OPCODE_NOTI_Dslam_STM1_AU4_LOS = (int)(0x7A0000B6);
  public static final int OPCODE_NOTI_Dslam_STM1_RS_LOF = (int)(0x7A0000B7);
  public static final int OPCODE_NOTI_Dslam_STM1_MS_LOF = (int)(0x7A0000B8);
  public static final int OPCODE_NOTI_Dslam_STM1_AU4_LOF = (int)(0x7A0000B9);
  public static final int OPCODE_NOTI_Dslam_STM1_RS_BER = (int)(0x7A0000BA);
  public static final int OPCODE_NOTI_Dslam_STM1_MS_BER = (int)(0x7A0000BB);
  public static final int OPCODE_NOTI_Dslam_STM1_AU4_BER = (int)(0x7A0000BC);
  public static final int OPCODE_NOTI_Dslam_STM1_RS_SD = (int)(0x7A0000BD);
  public static final int OPCODE_NOTI_Dslam_STM1_MS_SD = (int)(0x7A0000BE);
  public static final int OPCODE_NOTI_Dslam_STM1_AU4_SD = (int)(0x7A0000BF);
  public static final int OPCODE_NOTI_Dslam_STM1_RS_AIS = (int)(0x7A0000C0);
  public static final int OPCODE_NOTI_Dslam_STM1_MS_AIS = (int)(0x7A0000C1);
  public static final int OPCODE_NOTI_Dslam_STM1_AU4_AIS = (int)(0x7A0000C2);
  public static final int OPCODE_NOTI_Dslam_STM1_RS_LOC = (int)(0x7A0000C3);
  public static final int OPCODE_NOTI_Dslam_STM1_MS_LOC = (int)(0x7A0000C4);
  public static final int OPCODE_NOTI_Dslam_STM1_AU4_LOC = (int)(0x7A0000C5);
  public static final int OPCODE_NOTI_Dslam_STM1_RS_LOP = (int)(0x7A0000C6);
  public static final int OPCODE_NOTI_Dslam_STM1_MS_LOP = (int)(0x7A0000C7);
  public static final int OPCODE_NOTI_Dslam_STM1_AU4_LOP = (int)(0x7A0000C8);
  public static final int OPCODE_NOTI_Dslam_STM1_RS_RDI = (int)(0x7A0000C9);
  public static final int OPCODE_NOTI_Dslam_STM1_MS_RDI = (int)(0x7A0000CA);
  public static final int OPCODE_NOTI_Dslam_STM1_AU4_RDI = (int)(0x7A0000CB);
  public static final int OPCODE_NOTI_Dslam_ATM_Down_VP_LOC = (int)(0x7A0000CC);
  public static final int OPCODE_NOTI_Dslam_ATM_Down_VC_LOC = (int)(0x7A0000CD);
  public static final int OPCODE_NOTI_Dslam_ATM_Down_VP_SEG_AIS = (int)(0x7A0000CE);
  public static final int OPCODE_NOTI_Dslam_ATM_Down_VC_SEG_AIS = (int)(0x7A0000CF);
  public static final int OPCODE_NOTI_Dslam_ATM_Down_VP_SEG_RDI = (int)(0x7A0000D0);
  public static final int OPCODE_NOTI_Dslam_ATM_Down_VC_SEG_RDI = (int)(0x7A0000D1);
  public static final int OPCODE_NOTI_Dslam_ATM_Up_VC_LOC = (int)(0x7A0000D2);
  public static final int OPCODE_NOTI_Dslam_ATM_Up_VC_SEG_AIS = (int)(0x7A0000D3);
  public static final int OPCODE_NOTI_Dslam_ATM_Up_VC_SEG_RDI = (int)(0x7A0000D4);
  public static final int OPCODE_NOTI_Dslam_ATM_Down_VP_END_AIS = (int)(0x7A0000D5);
  public static final int OPCODE_NOTI_Dslam_ATM_Down_VC_END_AIS = (int)(0x7A0000D6);
  public static final int OPCODE_NOTI_Dslam_ATM_Up_VC_END_AIS = (int)(0x7A0000D7);
  public static final int OPCODE_NOTI_Dslam_ATM_Down_VP_END_RDI = (int)(0x7A0000D8);
  public static final int OPCODE_NOTI_Dslam_ATM_Down_VC_END_RDI = (int)(0x7A0000D9);
  public static final int OPCODE_NOTI_Dslam_ATM_Up_VC_END_RDI = (int)(0x7A0000DA);
  public static final int OPCODE_NOTI_Dslam_DSL_LOS = (int)(0x7A0000DB);
  public static final int OPCODE_NOTI_Dslam_DSL_LOF = (int)(0x7A0000DC);
  public static final int OPCODE_NOTI_Dslam_DSL_LOC = (int)(0x7A0000DD);
  public static final int OPCODE_NOTI_Dslam_DSL_NCD = (int)(0x7A0000DE);
  public static final int OPCODE_NOTI_Dslam_DSL_LOSWS = (int)(0x7A0000DF);
  public static final int OPCODE_NOTI_Dslam_DSL_UAS = (int)(0x7A0000E0);
  public static final int OPCODE_NOTI_Dslam_DSL_ES = (int)(0x7A0000E1);
  public static final int OPCODE_NOTI_Dslam_DSL_SES = (int)(0x7A0000E2);
  public static final int OPCODE_NOTI_Dslam_ShelfStatusAbnormal = (int)(0x7A0000E3);
  public static final int OPCODE_NOTI_Dslam_IPCFail = (int)(0x7A0000E4);

  // EMS Alarm
  public static final int OPCODE_NOTI_Ems_ProcAlarm = (int)(0x7A000E00);
  public static final int OPCODE_NOTI_Ems_CpuAlarm = (int)(0x7A000E01);
  public static final int OPCODE_NOTI_Ems_FssAlarm = (int)(0x7A000E02);
  public static final int OPCODE_NOTI_Ems_MemAlarm = (int)(0x7A000E03);
  public static final int OPCODE_NOTI_Ems_DbAlarm = (int)(0x7A000E04);
  public static final int OPCODE_NOTI_Ems_NetwAlarm = (int)(0x7A000E05);

  //--------------------------------------
  public static final int OPCODE_REQP_GetSysId_Config = (int)(0x7C000001);
  public static final int OPCODE_REQP_GetSubSysId_Config = (int)(0x7C000002);
  public static final int OPCODE_NOTI_Create_SysConfig = (int)(0x7C000030);
  public static final int OPCODE_NOTI_Delete_SysConfig = (int)(0x7C000031);
  public static final int OPCODE_NOTI_Change_SysConfig = (int)(0x7C000032);
  public static final int OPCODE_NOTI_Create_SubSysConfig = (int)(0x7C000033);
  public static final int OPCODE_NOTI_Delete_SubSysConfig = (int)(0x7C000034);
  public static final int OPCODE_NOTI_Change_SubSysConfig = (int)(0x7C000035);

  //NESS needs all AGW configuration (2007-11-15)
  public static final int OPCODE_REQP_GetAllSys_Config = (int)(0x7C000100);

  //--------------------------------------
  public static final int OPCODE_REQP_GetEms_Config4BcnNms = (int)(0x7C001000);
  public static final int OPCODE_REQP_GetSys_Config4BcnNms = (int)(0x7C001001);
  public static final int OPCODE_REQP_GetSubSys_Config4BcnNms = (int)(0x7C001002);
  public static final int OPCODE_NOTI_Dump_PerfData4BcnNms = (int)(0x7C001100);

  /***********************************************
  	* 2006`? `)? `?
  	***********************************************/
  public static final int OPCODE_REQP_EMS_CONFIG = (int)(0x7C002000);
  public static final int OPCODE_REQP_AGW_CONFIG = (int)(0x7C002001);
  public static final int OPCODE_REQP_CARD_CONFIG = (int)(0x7C002002);
  public static final int OPCODE_REQP_PORT_CONFIG = (int)(0x7C002003);
  public static final int OPCODE_REQP_NODEALL_CONFIG = (int)(0x7C002010);
  public static final int OPCODE_REQP_OBJSTATE_CONFIG = (int)(0x7C002011);
  public static final int OPCODE_REQP_MMC_CONFIG = (int)(0x7C002004);
  public static final int OPCODE_REQP_LOOPBACK_CONFIG = (int)(0x7C002005);
  public static final int OPCODE_REQP_RESET_CONFIG = (int)(0x7C002006);
  public static final int OPCODE_REQP_STATUS_CONFIG = (int)(0x7C002007);
  public static final int OPCODE_REQP_PKGSEND_CONFIG = (int)(0x7C002008);
  public static final int OPCODE_REQP_PKGDIST_CONFIG = (int)(0x7C002009);
  public static final int OPCODE_REQP_OP_CONFIG = (int)(0x7C00200A);
  public static final int OPCODE_REQP_OP_RESOURCE_CONFIG = (int)(0x7C00200B);
  public static final int OPCODE_ALARM_EVENT = (int)(0x7C00F001);
  public static final int OPCODE_STATE_EVENT = (int)(0x7C00F002);
  public static final int OPCODE_STATISTICS_EVENT = (int)(0x7C00F003);

  //--------------------------------------------------------------------------------------
  public static final int OPCODE_REQP_DialTone_Test = (int)(0x7B000001);

  //--------------------------------------------------------------------------------------
  public static final int OPCODE_NOTI_AgwSystem_LoadingState = (int)(0x7E000001);
  public static final int OPCODE_NOTI_AgwProcessor_LoadingState = (int)(0x7E000002);
  public static final int OPCODE_NOTI_AgwBlock_LoadingState = (int)(0x7E000003);

  //--------------------------------------------------------------------------------------
  public static final int OPCODE_REQP_SetMsgFilter = (int)(0x7F000001);
  public static final int OPCODE_REQP_GetMsgFilter = (int)(0x7F000002);

  //--------------------------------------------------------------------------------------
  public static final int OPCODE_NOTI_AgwEms_Start = (int)(0x6F000001);
  public static final int OPCODE_NOTI_AgwEms_Stop = (int)(0x6F000002);

  //--------------------------------------------------------------------------------------
  public static final int OPCODE_NOTI_AgwEms_ProcState = (int)(0x6E000001);
  public static final int OPCODE_NOTI_AgwEms_CpuState = (int)(0x6E000002);
  public static final int OPCODE_NOTI_AgwEms_HddState = (int)(0x6E000003);
  public static final int OPCODE_NOTI_AgwEms_DbState = (int)(0x6E000004);
  public static final int OPCODE_NOTI_AgwEms_MemState = (int)(0x6E000005);

  //--------------------------------------------------------------------------------------
  public static final int OPCODE_REQP_OP_VOPSERVICEIP_CONFIG = (int)(0x7C00200C);

  //--------------------------------------------------------------------------------------
  public static final int OPCODE_REQP_OP_CHANGECOLCODE_CONFIG = (int)(0x7C00200D);

  //--------------------------------------------------------------------------------------
  public static final int AGWTYPE_LG = (int)(90);
  public static final int AGWTYPE_SS = (int)(91);
  public static final int AGWTYPE_AL = (int)(92);
  public static final int AGWTYPE_LT = (int)(93);
  public static final int AGWTYPE_MR = (int)(94);
  public static final int AGWTYPE_ET = (int)(95);

  //--------------------------------------------------------------------------------------
  public static final int AGWEMSTYPE_LG = (int)(100);
  public static final int AGWEMSTYPE_SS = (int)(101);
  public static final int AGWEMSTYPE_AL = (int)(102);
  public static final int AGWEMSTYPE_LT = (int)(103);
  public static final int AGWEMSTYPE_MR = (int)(104);
  public static final int AGWEMSTYPE_ET = (int)(105);

  //--------------------------------------------------------------------------------------
  public static final int SVCGRP_Sys = (int)(1);
  public static final int SVCGRP_V5 = (int)(2);
  public static final int SVCGRP_Sli = (int)(3);
  public static final int SVCGRP_Utd = (int)(4);
  public static final int SVCGRP_Utf = (int)(5);
  public static final int SVCGRP_Prc = (int)(6);
  public static final int SVCGRP_pwr = (int)(7);
  public static final int SVCGRP_Swt = (int)(8);
  public static final int SVCGRP_Clk = (int)(9);
  public static final int SVCGRP_Sig = (int)(10);
  public static final int SVCGRP_Trk = (int)(11);
  public static final int SVCGRP_Tst = (int)(12);
  public static final int SVCGRP_Cbl = (int)(13);
  public static final int SVCGRP_Atm = (int)(14);
  public static final int SVCGRP_Dsl = (int)(15);
  public static final int SVCGRP_Env = (int)(16);

  //--------------------------------------------------------------------------------------
  public static final char OMIT_Byte = (char)('\176');
  public static final short OMIT_Short = (short)(0x7EEE);
  public static final int OMIT_Int = (int)(0x7EEEEEEE);
  public static final int OMIT_Long = (int)(0x7EEEEEEE);
} // interface xAGW
