package KTCosNMS;


/**
* KTCosNMS/xDSLAM.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/


//--------------------------------------------------------------------------------------
public interface xDSLAM extends xDSLAMOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface xDSLAM
