package KTCosNMS;


/**
* KTCosNMS/xEXCHOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/


//--------------------------------------------------------------------------------------
public interface xEXCHOperations 
{
} // interface xEXCHOperations
