package KTCosNMS;


/**
* KTCosNMS/xEXCH.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/


//--------------------------------------------------------------------------------------
public interface xEXCH extends xEXCHOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface xEXCH
