package KTCosNMS;


/**
* KTCosNMS/xKTSIOHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/


//--------------------------------------------------------------------------------------
abstract public class xKTSIOHelper
{
  private static String  _id = "IDL:KTCosNMS/xKTSIO:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.xKTSIO that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.xKTSIO extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (KTCosNMS.xKTSIOHelper.id (), "xKTSIO");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.xKTSIO read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_xKTSIOStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.xKTSIO value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static KTCosNMS.xKTSIO narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof KTCosNMS.xKTSIO)
      return (KTCosNMS.xKTSIO)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      KTCosNMS._xKTSIOStub stub = new KTCosNMS._xKTSIOStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static KTCosNMS.xKTSIO unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof KTCosNMS.xKTSIO)
      return (KTCosNMS.xKTSIO)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      KTCosNMS._xKTSIOStub stub = new KTCosNMS._xKTSIOStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
