package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/AdminStatusEnumHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/


//operStatus, ifoperstatus
abstract public class AdminStatusEnumHelper
{
  private static String  _id = "IDL:KTCosNMS/xAGW/AdminStatusEnum:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.xAGWPackage.AdminStatusEnum that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.xAGWPackage.AdminStatusEnum extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (KTCosNMS.xAGWPackage.AdminStatusEnumHelper.id (), "AdminStatusEnum", new String[] { "UNKNOWN_ADMINSTATUS", "TESTING_ADMINSTATUS", "UNBLOCK_ADMINSTATUS", "BLOCK_ADMINSTATUS", "SHUTTINGDOWN_ADMINSTATUS"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.xAGWPackage.AdminStatusEnum read (org.omg.CORBA.portable.InputStream istream)
  {
    return KTCosNMS.xAGWPackage.AdminStatusEnum.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.xAGWPackage.AdminStatusEnum value)
  {
    ostream.write_long (value.value ());
  }

}
