package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/AdminStatusEnumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/


//operStatus, ifoperstatus
public final class AdminStatusEnumHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.AdminStatusEnum value = null;

  public AdminStatusEnumHolder ()
  {
  }

  public AdminStatusEnumHolder (KTCosNMS.xAGWPackage.AdminStatusEnum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.AdminStatusEnumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.AdminStatusEnumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.AdminStatusEnumHelper.type ();
  }

}
