package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/CardInfoStHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

abstract public class CardInfoStHelper
{
  private static String  _id = "IDL:KTCosNMS/xAGW/CardInfoSt:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.xAGWPackage.CardInfoSt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.xAGWPackage.CardInfoSt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [12];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = KTCosNMS.xAGWPackage.CommonCardIdxStHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "varCommonCardIdxSt",
            _tcOf_members0,
            null);
          _tcOf_members0 = KTCosNMS.xAGWPackage.OperStatusEnumHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "operStatus",
            _tcOf_members0,
            null);
          _tcOf_members0 = KTCosNMS.xAGWPackage.ModeStatusEnumHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "modeStatus",
            _tcOf_members0,
            null);
          _tcOf_members0 = KTCosNMS.xAGWPackage.AdminStatusEnumHelper.type ();
          _members0[3] = new org.omg.CORBA.StructMember (
            "adminStatus",
            _tcOf_members0,
            null);
          _tcOf_members0 = KTCosNMS.xAGWPackage.LoopBackStatusEnumHelper.type ();
          _members0[4] = new org.omg.CORBA.StructMember (
            "loopBackStatus",
            _tcOf_members0,
            null);
          _tcOf_members0 = KTCosNMS.xAGWPackage.ModeStatusEnumHelper.type ();
          _members0[5] = new org.omg.CORBA.StructMember (
            "protectionStatus",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "alarmStatus",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "failReason",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[8] = new org.omg.CORBA.StructMember (
            "hwVersion",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[9] = new org.omg.CORBA.StructMember (
            "fwVersion",
            _tcOf_members0,
            null);
          _tcOf_members0 = KTCosNMS.xAGWPackage.CommonOptStHelper.type ();
          _members0[10] = new org.omg.CORBA.StructMember (
            "varCommonOptSt",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[11] = new org.omg.CORBA.StructMember (
            "emsMngCardInfo",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (KTCosNMS.xAGWPackage.CardInfoStHelper.id (), "CardInfoSt", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.xAGWPackage.CardInfoSt read (org.omg.CORBA.portable.InputStream istream)
  {
    KTCosNMS.xAGWPackage.CardInfoSt value = new KTCosNMS.xAGWPackage.CardInfoSt ();
    value.varCommonCardIdxSt = KTCosNMS.xAGWPackage.CommonCardIdxStHelper.read (istream);
    value.operStatus = KTCosNMS.xAGWPackage.OperStatusEnumHelper.read (istream);
    value.modeStatus = KTCosNMS.xAGWPackage.ModeStatusEnumHelper.read (istream);
    value.adminStatus = KTCosNMS.xAGWPackage.AdminStatusEnumHelper.read (istream);
    value.loopBackStatus = KTCosNMS.xAGWPackage.LoopBackStatusEnumHelper.read (istream);
    value.protectionStatus = KTCosNMS.xAGWPackage.ModeStatusEnumHelper.read (istream);
    value.alarmStatus = istream.read_string ();
    value.failReason = istream.read_string ();
    value.hwVersion = istream.read_string ();
    value.fwVersion = istream.read_string ();
    value.varCommonOptSt = KTCosNMS.xAGWPackage.CommonOptStHelper.read (istream);
    value.emsMngCardInfo = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.xAGWPackage.CardInfoSt value)
  {
    KTCosNMS.xAGWPackage.CommonCardIdxStHelper.write (ostream, value.varCommonCardIdxSt);
    KTCosNMS.xAGWPackage.OperStatusEnumHelper.write (ostream, value.operStatus);
    KTCosNMS.xAGWPackage.ModeStatusEnumHelper.write (ostream, value.modeStatus);
    KTCosNMS.xAGWPackage.AdminStatusEnumHelper.write (ostream, value.adminStatus);
    KTCosNMS.xAGWPackage.LoopBackStatusEnumHelper.write (ostream, value.loopBackStatus);
    KTCosNMS.xAGWPackage.ModeStatusEnumHelper.write (ostream, value.protectionStatus);
    ostream.write_string (value.alarmStatus);
    ostream.write_string (value.failReason);
    ostream.write_string (value.hwVersion);
    ostream.write_string (value.fwVersion);
    KTCosNMS.xAGWPackage.CommonOptStHelper.write (ostream, value.varCommonOptSt);
    ostream.write_string (value.emsMngCardInfo);
  }

}
