package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/CardTypeEnumHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/


//----------------------------------------------------------------------------------
abstract public class CardTypeEnumHelper
{
  private static String  _id = "IDL:KTCosNMS/xAGW/CardTypeEnum:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.xAGWPackage.CardTypeEnum that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.xAGWPackage.CardTypeEnum extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (KTCosNMS.xAGWPackage.CardTypeEnumHelper.id (), "CardTypeEnum", new String[] { "UNKNOWN_CARDTYPE", "SAPC_CARDTYPE", "GPIC_CARDTYPE", "GSIC_CARDTYPE", "VOPC_CARDTYPE", "THSC_CARDTYPE", "GLSC_CARDTYPE", "POWER_CARDTYPE", "FAN_CARDTYPE", "NONE_CARDTYPE", "SCMU_CARDTYPE", "PSU_CARDTYPE", "NIU_CARDTYPE", "NSDU_CARDTYPE", "LTIU_CARDTYPE", "HTIU_CARDTYPE", "CMU_CARDTYPE", "SLU_64P_CARDTYPE", "SLU_64E_CARDTYPE", "MCUN_CS_CARDTYPE", "VPU_A02_CARDTYPE", "SLU_32C_CARDTYPE", "DTU_A_CARDTYPE", "MCU_SUB_CARDTYPE", "INVC_CARDTYPE", "INRC_CARDTYPE", "MCMC_S_CARDTYPE", "MC_RC_CARDTYPE", "POTC_C_CARDTYPE", "ESIC_CARDTYPE", "ESRC12T_CARDTYPE", "IOE1_CARDTYPE", "RG_PACK_CARDTYPE", "CIU_CARDTYPE", "IPFM_CARDTYPE", "COMDAC_CARDTYPE", "POTS_CARDTYPE", "ICAP_CARDTYPE", "TEST_PACK_CARDTYPE", "ESIM_CARDTYPE", "SHDSL_CARDTYPE", "RGU_CARDTYPE", "PFU_CARDTYPE", "MEU_CARDTYPE", "SVU_CARDTYPE", "SEU_CARDTYPE", "DPU_CARDTYPE", "APU_CARDTYPE"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.xAGWPackage.CardTypeEnum read (org.omg.CORBA.portable.InputStream istream)
  {
    return KTCosNMS.xAGWPackage.CardTypeEnum.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.xAGWPackage.CardTypeEnum value)
  {
    ostream.write_long (value.value ());
  }

}
