package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/CardInfoStHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class CardInfoStHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.CardInfoSt value = null;

  public CardInfoStHolder ()
  {
  }

  public CardInfoStHolder (KTCosNMS.xAGWPackage.CardInfoSt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.CardInfoStHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.CardInfoStHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.CardInfoStHelper.type ();
  }

}
