package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/CardTypeEnumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/


//----------------------------------------------------------------------------------
public final class CardTypeEnumHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.CardTypeEnum value = null;

  public CardTypeEnumHolder ()
  {
  }

  public CardTypeEnumHolder (KTCosNMS.xAGWPackage.CardTypeEnum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.CardTypeEnumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.CardTypeEnumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.CardTypeEnumHelper.type ();
  }

}
