package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/ChangeAgwIdSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public final class ChangeAgwIdSt implements org.omg.CORBA.portable.IDLEntity
{
  public String emsId = null;
  public String agwId = null;
  public String managementIp = null;

  public ChangeAgwIdSt ()
  {
  } // ctor

  public ChangeAgwIdSt (String _emsId, String _agwId, String _managementIp)
  {
    emsId = _emsId;
    agwId = _agwId;
    managementIp = _managementIp;
  } // ctor

} // class ChangeAgwIdSt
