package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/CommonOptSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public final class CommonOptSt implements org.omg.CORBA.portable.IDLEntity
{
  public String vendorName = null;

  // `?`? `??
  public String manufactureDate = null;

  // `?`?`?
  public String serialNumber = null;

  // `??`?8
  public String description = null;

  public CommonOptSt ()
  {
  } // ctor

  public CommonOptSt (String _vendorName, String _manufactureDate, String _serialNumber, String _description)
  {
    vendorName = _vendorName;
    manufactureDate = _manufactureDate;
    serialNumber = _serialNumber;
    description = _description;
  } // ctor

} // class CommonOptSt
