package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/CommonCardIdxSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class CommonCardIdxSt implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;
  public String rackId = null;
  public String shelfId = null;
  public String slotId = null;
  public String cardId = null;
  public String cardType = null;

  public CommonCardIdxSt ()
  {
  } // ctor

  public CommonCardIdxSt (String _agwId, String _rackId, String _shelfId, String _slotId, String _cardId, String _cardType)
  {
    agwId = _agwId;
    rackId = _rackId;
    shelfId = _shelfId;
    slotId = _slotId;
    cardId = _cardId;
    cardType = _cardType;
  } // ctor

} // class CommonCardIdxSt
