package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/CommonPortIdxSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class CommonPortIdxSt implements org.omg.CORBA.portable.IDLEntity
{
  public KTCosNMS.xAGWPackage.CommonCardIdxSt varCommonCardIdxSt = null;
  public String portId = null;
  public KTCosNMS.xAGWPackage.PortTypeEnum portType = null;
  public String portName = null;

  public CommonPortIdxSt ()
  {
  } // ctor

  public CommonPortIdxSt (KTCosNMS.xAGWPackage.CommonCardIdxSt _varCommonCardIdxSt, String _portId, KTCosNMS.xAGWPackage.PortTypeEnum _portType, String _portName)
  {
    varCommonCardIdxSt = _varCommonCardIdxSt;
    portId = _portId;
    portType = _portType;
    portName = _portName;
  } // ctor

} // class CommonPortIdxSt
