package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/DeviceTypeEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public class DeviceTypeEnum implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 6;
  private static KTCosNMS.xAGWPackage.DeviceTypeEnum[] __array = new KTCosNMS.xAGWPackage.DeviceTypeEnum [__size];

  public static final int _UNKNOWN_DEVICETYPE = 0;
  public static final KTCosNMS.xAGWPackage.DeviceTypeEnum UNKNOWN_DEVICETYPE = new KTCosNMS.xAGWPackage.DeviceTypeEnum(_UNKNOWN_DEVICETYPE);
  public static final int _POWER_DEVICETYPE = 1;
  public static final KTCosNMS.xAGWPackage.DeviceTypeEnum POWER_DEVICETYPE = new KTCosNMS.xAGWPackage.DeviceTypeEnum(_POWER_DEVICETYPE);
  public static final int _FAN_DEVICETYPE = 2;
  public static final KTCosNMS.xAGWPackage.DeviceTypeEnum FAN_DEVICETYPE = new KTCosNMS.xAGWPackage.DeviceTypeEnum(_FAN_DEVICETYPE);
  public static final int _PROCESSOR_DEVICETYPE = 3;
  public static final KTCosNMS.xAGWPackage.DeviceTypeEnum PROCESSOR_DEVICETYPE = new KTCosNMS.xAGWPackage.DeviceTypeEnum(_PROCESSOR_DEVICETYPE);
  public static final int _STORAGE_DEVICETYPE = 4;
  public static final KTCosNMS.xAGWPackage.DeviceTypeEnum STORAGE_DEVICETYPE = new KTCosNMS.xAGWPackage.DeviceTypeEnum(_STORAGE_DEVICETYPE);
  public static final int _DSP_DEVICETYPE = 5;
  public static final KTCosNMS.xAGWPackage.DeviceTypeEnum DSP_DEVICETYPE = new KTCosNMS.xAGWPackage.DeviceTypeEnum(_DSP_DEVICETYPE);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.xAGWPackage.DeviceTypeEnum from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected DeviceTypeEnum (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class DeviceTypeEnum
