package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/DeviceTypeEnumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022년 10월 19일 수요일 오후 6시 39분 28초 KST
*/

public final class DeviceTypeEnumHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.DeviceTypeEnum value = null;

  public DeviceTypeEnumHolder ()
  {
  }

  public DeviceTypeEnumHolder (KTCosNMS.xAGWPackage.DeviceTypeEnum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.DeviceTypeEnumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.DeviceTypeEnumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.DeviceTypeEnumHelper.type ();
  }

}
