package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/DiskInfoSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class DiskInfoSt implements org.omg.CORBA.portable.IDLEntity
{
  public String diskPath = null;

  // X \
  public int diskUsage = (int)0;

  public DiskInfoSt ()
  {
  } // ctor

  public DiskInfoSt (String _diskPath, int _diskUsage)
  {
    diskPath = _diskPath;
    diskUsage = _diskUsage;
  } // ctor

} // class DiskInfoSt
