package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/DistributePkgSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class DistributePkgSt implements org.omg.CORBA.portable.IDLEntity
{
  public KTCosNMS.xAGWPackage.ObjectTypeEnum objectType = null;
  public String agwId = null;
  public String rackId = null;
  public String shelfId = null;
  public String slotId = null;
  public String cardId = null;
  public String pkgName = null;
  public String swVersion = null;
  public int pkgSize = (int)0;
  public String time = null;

  public DistributePkgSt ()
  {
  } // ctor

  public DistributePkgSt (KTCosNMS.xAGWPackage.ObjectTypeEnum _objectType, String _agwId, String _rackId, String _shelfId, String _slotId, String _cardId, String _pkgName, String _swVersion, int _pkgSize, String _time)
  {
    objectType = _objectType;
    agwId = _agwId;
    rackId = _rackId;
    shelfId = _shelfId;
    slotId = _slotId;
    cardId = _cardId;
    pkgName = _pkgName;
    swVersion = _swVersion;
    pkgSize = _pkgSize;
    time = _time;
  } // ctor

} // class DistributePkgSt
