package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/EmsInfoStHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class EmsInfoStHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.EmsInfoSt value = null;

  public EmsInfoStHolder ()
  {
  }

  public EmsInfoStHolder (KTCosNMS.xAGWPackage.EmsInfoSt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.EmsInfoStHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.EmsInfoStHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.EmsInfoStHelper.type ();
  }

}
