package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/enSysState4BcnNmsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class enSysState4BcnNmsHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.enSysState4BcnNms value = null;

  public enSysState4BcnNmsHolder ()
  {
  }

  public enSysState4BcnNmsHolder (KTCosNMS.xAGWPackage.enSysState4BcnNms initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.enSysState4BcnNmsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.enSysState4BcnNmsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.enSysState4BcnNmsHelper.type ();
  }

}
