package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/enSysState4BcnNms.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public class enSysState4BcnNms implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 7;
  private static KTCosNMS.xAGWPackage.enSysState4BcnNms[] __array = new KTCosNMS.xAGWPackage.enSysState4BcnNms [__size];

  public static final int _SYSSTATE_Unknown = 0;
  public static final KTCosNMS.xAGWPackage.enSysState4BcnNms SYSSTATE_Unknown = new KTCosNMS.xAGWPackage.enSysState4BcnNms(_SYSSTATE_Unknown);
  public static final int _SYSSTATE_Not_Installed = 1;
  public static final KTCosNMS.xAGWPackage.enSysState4BcnNms SYSSTATE_Not_Installed = new KTCosNMS.xAGWPackage.enSysState4BcnNms(_SYSSTATE_Not_Installed);
  public static final int _SYSSTATE_Installed = 2;
  public static final KTCosNMS.xAGWPackage.enSysState4BcnNms SYSSTATE_Installed = new KTCosNMS.xAGWPackage.enSysState4BcnNms(_SYSSTATE_Installed);
  public static final int _SYSSTATE_Inactive = 3;
  public static final KTCosNMS.xAGWPackage.enSysState4BcnNms SYSSTATE_Inactive = new KTCosNMS.xAGWPackage.enSysState4BcnNms(_SYSSTATE_Inactive);
  public static final int _SYSSTATE_Idl = 4;
  public static final KTCosNMS.xAGWPackage.enSysState4BcnNms SYSSTATE_Idl = new KTCosNMS.xAGWPackage.enSysState4BcnNms(_SYSSTATE_Idl);
  public static final int _SYSSTATE_Active = 5;
  public static final KTCosNMS.xAGWPackage.enSysState4BcnNms SYSSTATE_Active = new KTCosNMS.xAGWPackage.enSysState4BcnNms(_SYSSTATE_Active);
  public static final int _SYSSTATE_Busy = 6;
  public static final KTCosNMS.xAGWPackage.enSysState4BcnNms SYSSTATE_Busy = new KTCosNMS.xAGWPackage.enSysState4BcnNms(_SYSSTATE_Busy);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.xAGWPackage.enSysState4BcnNms from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected enSysState4BcnNms (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class enSysState4BcnNms
