package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/EquipInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class EquipInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.EquipInfo value = null;

  public EquipInfoHolder ()
  {
  }

  public EquipInfoHolder (KTCosNMS.xAGWPackage.EquipInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.EquipInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.EquipInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.EquipInfoHelper.type ();
  }

}
