package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/ExecuteMmcStHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

abstract public class ExecuteMmcStHelper
{
  private static String  _id = "IDL:KTCosNMS/xAGW/ExecuteMmcSt:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.xAGWPackage.ExecuteMmcSt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.xAGWPackage.ExecuteMmcSt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "agwId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "taskId",
            _tcOf_members0,
            null);
          _tcOf_members0 = KTCosNMS.xAGWPackage.ResultTypeEnumHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "resultType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "command",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (KTCosNMS.xAGWPackage.ExecuteMmcStHelper.id (), "ExecuteMmcSt", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.xAGWPackage.ExecuteMmcSt read (org.omg.CORBA.portable.InputStream istream)
  {
    KTCosNMS.xAGWPackage.ExecuteMmcSt value = new KTCosNMS.xAGWPackage.ExecuteMmcSt ();
    value.agwId = istream.read_string ();
    value.taskId = istream.read_string ();
    value.resultType = KTCosNMS.xAGWPackage.ResultTypeEnumHelper.read (istream);
    value.command = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.xAGWPackage.ExecuteMmcSt value)
  {
    ostream.write_string (value.agwId);
    ostream.write_string (value.taskId);
    KTCosNMS.xAGWPackage.ResultTypeEnumHelper.write (ostream, value.resultType);
    ostream.write_string (value.command);
  }

}
