package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/ExecuteMmcSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class ExecuteMmcSt implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;
  public String taskId = null;
  public KTCosNMS.xAGWPackage.ResultTypeEnum resultType = null;
  public String command = null;

  public ExecuteMmcSt ()
  {
  } // ctor

  public ExecuteMmcSt (String _agwId, String _taskId, KTCosNMS.xAGWPackage.ResultTypeEnum _resultType, String _command)
  {
    agwId = _agwId;
    taskId = _taskId;
    resultType = _resultType;
    command = _command;
  } // ctor

} // class ExecuteMmcSt
