package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/GetObjectSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public final class GetObjectSt implements org.omg.CORBA.portable.IDLEntity
{
  public KTCosNMS.xAGWPackage.ObjectTypeEnum objectType = null;
  public String emsId = null;
  public String systemId = null;
  public String rackId = null;
  public String shelfId = null;
  public String slotId = null;
  public String deviceId = null;
  public String portId = null;
  public String ifId = null;

  public GetObjectSt ()
  {
  } // ctor

  public GetObjectSt (KTCosNMS.xAGWPackage.ObjectTypeEnum _objectType, String _emsId, String _systemId, String _rackId, String _shelfId, String _slotId, String _deviceId, String _portId, String _ifId)
  {
    objectType = _objectType;
    emsId = _emsId;
    systemId = _systemId;
    rackId = _rackId;
    shelfId = _shelfId;
    slotId = _slotId;
    deviceId = _deviceId;
    portId = _portId;
    ifId = _ifId;
  } // ctor

} // class GetObjectSt
