package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/IfSpeedEnumHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

abstract public class IfSpeedEnumHelper
{
  private static String  _id = "IDL:KTCosNMS/xAGW/IfSpeedEnum:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.xAGWPackage.IfSpeedEnum that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.xAGWPackage.IfSpeedEnum extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (KTCosNMS.xAGWPackage.IfSpeedEnumHelper.id (), "IfSpeedEnum", new String[] { "UNKNOWN_IFSPEED", "FE_IFSPEED", "GE_IFSPEED", "T1_IFSPEED", "E1_IFSPEED", "STM1_IFSPEED"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.xAGWPackage.IfSpeedEnum read (org.omg.CORBA.portable.InputStream istream)
  {
    return KTCosNMS.xAGWPackage.IfSpeedEnum.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.xAGWPackage.IfSpeedEnum value)
  {
    ostream.write_long (value.value ());
  }

}
