package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/IfTypeEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public class IfTypeEnum implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 7;
  private static KTCosNMS.xAGWPackage.IfTypeEnum[] __array = new KTCosNMS.xAGWPackage.IfTypeEnum [__size];

  public static final int _UNKNOWN_IFTYPE = 0;
  public static final KTCosNMS.xAGWPackage.IfTypeEnum UNKNOWN_IFTYPE = new KTCosNMS.xAGWPackage.IfTypeEnum(_UNKNOWN_IFTYPE);
  public static final int _FE_IFTYPE = 1;
  public static final KTCosNMS.xAGWPackage.IfTypeEnum FE_IFTYPE = new KTCosNMS.xAGWPackage.IfTypeEnum(_FE_IFTYPE);
  public static final int _GE_IFTYPE = 2;
  public static final KTCosNMS.xAGWPackage.IfTypeEnum GE_IFTYPE = new KTCosNMS.xAGWPackage.IfTypeEnum(_GE_IFTYPE);
  public static final int _T1_IFTYPE = 3;
  public static final KTCosNMS.xAGWPackage.IfTypeEnum T1_IFTYPE = new KTCosNMS.xAGWPackage.IfTypeEnum(_T1_IFTYPE);
  public static final int _E1_IFTYPE = 4;
  public static final KTCosNMS.xAGWPackage.IfTypeEnum E1_IFTYPE = new KTCosNMS.xAGWPackage.IfTypeEnum(_E1_IFTYPE);
  public static final int _STM1_IFTYPE = 5;
  public static final KTCosNMS.xAGWPackage.IfTypeEnum STM1_IFTYPE = new KTCosNMS.xAGWPackage.IfTypeEnum(_STM1_IFTYPE);
  public static final int _IPINTERFACE_IFTYPE = 6;
  public static final KTCosNMS.xAGWPackage.IfTypeEnum IPINTERFACE_IFTYPE = new KTCosNMS.xAGWPackage.IfTypeEnum(_IPINTERFACE_IFTYPE);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.xAGWPackage.IfTypeEnum from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected IfTypeEnum (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class IfTypeEnum
