package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/IfTypeEnumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class IfTypeEnumHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.IfTypeEnum value = null;

  public IfTypeEnumHolder ()
  {
  }

  public IfTypeEnumHolder (KTCosNMS.xAGWPackage.IfTypeEnum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.IfTypeEnumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.IfTypeEnumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.IfTypeEnumHelper.type ();
  }

}
