package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/InterfaceInfoSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class InterfaceInfoSt implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;
  public String Ifid = null;
  public KTCosNMS.xAGWPackage.IfTypeEnum ifType = null;
  public KTCosNMS.xAGWPackage.IfSpeedEnum ifSpeed = null;
  public KTCosNMS.xAGWPackage.OperStatusEnum ifOperStatus = null;
  public KTCosNMS.xAGWPackage.AdminStatusEnum ifAdminStatus = null;
  public String ipAddress = null;
  public String netMask = null;
  public String physicalAddress = null;
  public int aisStatus = (int)0;
  public int dscpValue = (int)0;
  public KTCosNMS.xAGWPackage.LoopBackStatusEnum loopBackStatus = null;
  public String failReason = null;
  public String alarmStatus = null;

  public InterfaceInfoSt ()
  {
  } // ctor

  public InterfaceInfoSt (String _agwId, String _Ifid, KTCosNMS.xAGWPackage.IfTypeEnum _ifType, KTCosNMS.xAGWPackage.IfSpeedEnum _ifSpeed, KTCosNMS.xAGWPackage.OperStatusEnum _ifOperStatus, KTCosNMS.xAGWPackage.AdminStatusEnum _ifAdminStatus, String _ipAddress, String _netMask, String _physicalAddress, int _aisStatus, int _dscpValue, KTCosNMS.xAGWPackage.LoopBackStatusEnum _loopBackStatus, String _failReason, String _alarmStatus)
  {
    agwId = _agwId;
    Ifid = _Ifid;
    ifType = _ifType;
    ifSpeed = _ifSpeed;
    ifOperStatus = _ifOperStatus;
    ifAdminStatus = _ifAdminStatus;
    ipAddress = _ipAddress;
    netMask = _netMask;
    physicalAddress = _physicalAddress;
    aisStatus = _aisStatus;
    dscpValue = _dscpValue;
    loopBackStatus = _loopBackStatus;
    failReason = _failReason;
    alarmStatus = _alarmStatus;
  } // ctor

} // class InterfaceInfoSt
