package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/LoopbackStHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class LoopbackStHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.LoopbackSt value = null;

  public LoopbackStHolder ()
  {
  }

  public LoopbackStHolder (KTCosNMS.xAGWPackage.LoopbackSt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.LoopbackStHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.LoopbackStHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.LoopbackStHelper.type ();
  }

}
