package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/LoopBackStatusEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/


//----------------------------------------------------------------------------------
public class LoopBackStatusEnum implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static KTCosNMS.xAGWPackage.LoopBackStatusEnum[] __array = new KTCosNMS.xAGWPackage.LoopBackStatusEnum [__size];

  public static final int _NOLOOP_LOOPBACKSTATUS = 0;
  public static final KTCosNMS.xAGWPackage.LoopBackStatusEnum NOLOOP_LOOPBACKSTATUS = new KTCosNMS.xAGWPackage.LoopBackStatusEnum(_NOLOOP_LOOPBACKSTATUS);
  public static final int _REMOTE_LOOPBACKSTATUS = 1;
  public static final KTCosNMS.xAGWPackage.LoopBackStatusEnum REMOTE_LOOPBACKSTATUS = new KTCosNMS.xAGWPackage.LoopBackStatusEnum(_REMOTE_LOOPBACKSTATUS);
  public static final int _LOCAL_LOOPBACKSTATUS = 2;
  public static final KTCosNMS.xAGWPackage.LoopBackStatusEnum LOCAL_LOOPBACKSTATUS = new KTCosNMS.xAGWPackage.LoopBackStatusEnum(_LOCAL_LOOPBACKSTATUS);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.xAGWPackage.LoopBackStatusEnum from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected LoopBackStatusEnum (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class LoopBackStatusEnum
