package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/NodeInfoEventStHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class NodeInfoEventStHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.NodeInfoEventSt value = null;

  public NodeInfoEventStHolder ()
  {
  }

  public NodeInfoEventStHolder (KTCosNMS.xAGWPackage.NodeInfoEventSt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.NodeInfoEventStHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.NodeInfoEventStHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.NodeInfoEventStHelper.type ();
  }

}
