package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/NodeInfoEventSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class NodeInfoEventSt implements org.omg.CORBA.portable.IDLEntity
{
  public String emsId = null;
  public String agwId = null;
  public int keyValue = (int)0;
  public String userId = null;
  public String passWord = null;
  public String fileLocation = null;
  public String fileSize = null;
  public String eventTime = null;

  public NodeInfoEventSt ()
  {
  } // ctor

  public NodeInfoEventSt (String _emsId, String _agwId, int _keyValue, String _userId, String _passWord, String _fileLocation, String _fileSize, String _eventTime)
  {
    emsId = _emsId;
    agwId = _agwId;
    keyValue = _keyValue;
    userId = _userId;
    passWord = _passWord;
    fileLocation = _fileLocation;
    fileSize = _fileSize;
    eventTime = _eventTime;
  } // ctor

} // class NodeInfoEventSt
