package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/OperationSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public final class OperationSt implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;
  public String rackId = null;
  public String shelfId = null;
  public String slotId = null;
  public String cardId = null;
  public KTCosNMS.xAGWPackage.OpEnum op = null;

  public OperationSt ()
  {
  } // ctor

  public OperationSt (String _agwId, String _rackId, String _shelfId, String _slotId, String _cardId, KTCosNMS.xAGWPackage.OpEnum _op)
  {
    agwId = _agwId;
    rackId = _rackId;
    shelfId = _shelfId;
    slotId = _slotId;
    cardId = _cardId;
    op = _op;
  } // ctor

} // class OperationSt
