package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/OperStatusEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public class OperStatusEnum implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static KTCosNMS.xAGWPackage.OperStatusEnum[] __array = new KTCosNMS.xAGWPackage.OperStatusEnum [__size];

  public static final int _UNKNOWN_OPERSTATUS = 0;
  public static final KTCosNMS.xAGWPackage.OperStatusEnum UNKNOWN_OPERSTATUS = new KTCosNMS.xAGWPackage.OperStatusEnum(_UNKNOWN_OPERSTATUS);
  public static final int _UP_OPERSTATUS = 1;
  public static final KTCosNMS.xAGWPackage.OperStatusEnum UP_OPERSTATUS = new KTCosNMS.xAGWPackage.OperStatusEnum(_UP_OPERSTATUS);
  public static final int _DOWN_OPERSTATUS = 2;
  public static final KTCosNMS.xAGWPackage.OperStatusEnum DOWN_OPERSTATUS = new KTCosNMS.xAGWPackage.OperStatusEnum(_DOWN_OPERSTATUS);
  public static final int _TESTING_OPERSTATUS = 3;
  public static final KTCosNMS.xAGWPackage.OperStatusEnum TESTING_OPERSTATUS = new KTCosNMS.xAGWPackage.OperStatusEnum(_TESTING_OPERSTATUS);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.xAGWPackage.OperStatusEnum from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected OperStatusEnum (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class OperStatusEnum
