package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/PortInfoStHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

abstract public class PortInfoStHelper
{
  private static String  _id = "IDL:KTCosNMS/xAGW/PortInfoSt:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.xAGWPackage.PortInfoSt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.xAGWPackage.PortInfoSt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = KTCosNMS.xAGWPackage.CommonPortIdxStHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "varCommonPortIdxSt",
            _tcOf_members0,
            null);
          _tcOf_members0 = KTCosNMS.xAGWPackage.OperStatusEnumHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "operStatus",
            _tcOf_members0,
            null);
          _tcOf_members0 = KTCosNMS.xAGWPackage.EquipStatusEnumHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "equipStatus",
            _tcOf_members0,
            null);
          _tcOf_members0 = KTCosNMS.xAGWPackage.InterfaceInfoStHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (KTCosNMS.xAGWPackage.InterfaceInfoStSeqHelper.id (), "InterfaceInfoStSeq", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "ifIdList",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (KTCosNMS.xAGWPackage.PortInfoStHelper.id (), "PortInfoSt", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.xAGWPackage.PortInfoSt read (org.omg.CORBA.portable.InputStream istream)
  {
    KTCosNMS.xAGWPackage.PortInfoSt value = new KTCosNMS.xAGWPackage.PortInfoSt ();
    value.varCommonPortIdxSt = KTCosNMS.xAGWPackage.CommonPortIdxStHelper.read (istream);
    value.operStatus = KTCosNMS.xAGWPackage.OperStatusEnumHelper.read (istream);
    value.equipStatus = KTCosNMS.xAGWPackage.EquipStatusEnumHelper.read (istream);
    value.ifIdList = KTCosNMS.xAGWPackage.InterfaceInfoStSeqHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.xAGWPackage.PortInfoSt value)
  {
    KTCosNMS.xAGWPackage.CommonPortIdxStHelper.write (ostream, value.varCommonPortIdxSt);
    KTCosNMS.xAGWPackage.OperStatusEnumHelper.write (ostream, value.operStatus);
    KTCosNMS.xAGWPackage.EquipStatusEnumHelper.write (ostream, value.equipStatus);
    KTCosNMS.xAGWPackage.InterfaceInfoStSeqHelper.write (ostream, value.ifIdList);
  }

}
