package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/ResourceInfoSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public final class ResourceInfoSt implements org.omg.CORBA.portable.IDLEntity
{
  public String systemId = null;

  // `??`? ID
  public int cpuUsage = (int)0;

  // cpu `?I?(%)
  public int memoryUsage = (int)0;

  // `(? `?I?(%)
  public KTCosNMS.xAGWPackage.DiskInfoSt diskInfo[] = null;

  public ResourceInfoSt ()
  {
  } // ctor

  public ResourceInfoSt (String _systemId, int _cpuUsage, int _memoryUsage, KTCosNMS.xAGWPackage.DiskInfoSt[] _diskInfo)
  {
    systemId = _systemId;
    cpuUsage = _cpuUsage;
    memoryUsage = _memoryUsage;
    diskInfo = _diskInfo;
  } // ctor

} // class ResourceInfoSt
