package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/ResourceInfoSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class ResourceInfoSt implements org.omg.CORBA.portable.IDLEntity
{
  public String systemId = null;

  // ?\ ID
  public int cpuUsage = (int)0;

  // cpu ???(%)
  public int memoryUsage = (int)0;

  // T? ???(%)
  public KTCosNMS.xAGWPackage.DiskInfoSt diskInfo[] = null;

  public ResourceInfoSt ()
  {
  } // ctor

  public ResourceInfoSt (String _systemId, int _cpuUsage, int _memoryUsage, KTCosNMS.xAGWPackage.DiskInfoSt[] _diskInfo)
  {
    systemId = _systemId;
    cpuUsage = _cpuUsage;
    memoryUsage = _memoryUsage;
    diskInfo = _diskInfo;
  } // ctor

} // class ResourceInfoSt
