package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/ResultPkgSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class ResultPkgSt implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;
  public String rackId = null;
  public String shelfId = null;
  public String slotId = null;
  public String cardId = null;
  public KTCosNMS.xAGWPackage.CompleteTypeEnum completeType = null;
  public String bfVersion = null;
  public String bfPkgName = null;
  public String upVersion = null;
  public String upPkgName = null;
  public String failReason = null;

  public ResultPkgSt ()
  {
  } // ctor

  public ResultPkgSt (String _agwId, String _rackId, String _shelfId, String _slotId, String _cardId, KTCosNMS.xAGWPackage.CompleteTypeEnum _completeType, String _bfVersion, String _bfPkgName, String _upVersion, String _upPkgName, String _failReason)
  {
    agwId = _agwId;
    rackId = _rackId;
    shelfId = _shelfId;
    slotId = _slotId;
    cardId = _cardId;
    completeType = _completeType;
    bfVersion = _bfVersion;
    bfPkgName = _bfPkgName;
    upVersion = _upVersion;
    upPkgName = _upPkgName;
    failReason = _failReason;
  } // ctor

} // class ResultPkgSt
