package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/ResultPkgStSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class ResultPkgStSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.ResultPkgSt value[] = null;

  public ResultPkgStSeqHolder ()
  {
  }

  public ResultPkgStSeqHolder (KTCosNMS.xAGWPackage.ResultPkgSt[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.ResultPkgStSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.ResultPkgStSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.ResultPkgStSeqHelper.type ();
  }

}
