package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/ResultStatusSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public final class ResultStatusSt implements org.omg.CORBA.portable.IDLEntity
{
  public String rackId = null;
  public String shelfId = null;
  public String slotId = null;
  public String cardId = null;
  public String portId = null;
  public KTCosNMS.xAGWPackage.AdminStatusEnum adminStatus = null;
  public String alarmStatus = null;
  public KTCosNMS.xAGWPackage.LoopBackStatusEnum lookbackStatus = null;
  public KTCosNMS.xAGWPackage.ModeStatusEnum protectionStatus = null;
  public String swVersion = null;
  public String fwVersion = null;
  public String failReason = null;

  public ResultStatusSt ()
  {
  } // ctor

  public ResultStatusSt (String _rackId, String _shelfId, String _slotId, String _cardId, String _portId, KTCosNMS.xAGWPackage.AdminStatusEnum _adminStatus, String _alarmStatus, KTCosNMS.xAGWPackage.LoopBackStatusEnum _lookbackStatus, KTCosNMS.xAGWPackage.ModeStatusEnum _protectionStatus, String _swVersion, String _fwVersion, String _failReason)
  {
    rackId = _rackId;
    shelfId = _shelfId;
    slotId = _slotId;
    cardId = _cardId;
    portId = _portId;
    adminStatus = _adminStatus;
    alarmStatus = _alarmStatus;
    lookbackStatus = _lookbackStatus;
    protectionStatus = _protectionStatus;
    swVersion = _swVersion;
    fwVersion = _fwVersion;
    failReason = _failReason;
  } // ctor

} // class ResultStatusSt
