package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/ResultTypeEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/


//----------------------------------------------------------------------------------
public class ResultTypeEnum implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 2;
  private static KTCosNMS.xAGWPackage.ResultTypeEnum[] __array = new KTCosNMS.xAGWPackage.ResultTypeEnum [__size];

  public static final int _SYNC_RESULTTYPE = 0;
  public static final KTCosNMS.xAGWPackage.ResultTypeEnum SYNC_RESULTTYPE = new KTCosNMS.xAGWPackage.ResultTypeEnum(_SYNC_RESULTTYPE);
  public static final int _ASYNC_RESULTTYPE = 1;
  public static final KTCosNMS.xAGWPackage.ResultTypeEnum ASYNC_RESULTTYPE = new KTCosNMS.xAGWPackage.ResultTypeEnum(_ASYNC_RESULTTYPE);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.xAGWPackage.ResultTypeEnum from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected ResultTypeEnum (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class ResultTypeEnum
