package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/ResultSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class ResultSt implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;
  public String taskId = null;

  // ?9 ID
  public KTCosNMS.xAGWPackage.StringSt varString[] = null;

  // ? ?
  public String failReason = null;

  // ?(? x
  public String time = null;

  public ResultSt ()
  {
  } // ctor

  public ResultSt (String _agwId, String _taskId, KTCosNMS.xAGWPackage.StringSt[] _varString, String _failReason, String _time)
  {
    agwId = _agwId;
    taskId = _taskId;
    varString = _varString;
    failReason = _failReason;
    time = _time;
  } // ctor

} // class ResultSt
