package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/RslpSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public final class RslpSt implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;
  public String rackId = null;
  public String shelfId = null;
  public String slotId = null;
  public String cardId = null;
  public String portId = null;

  public RslpSt ()
  {
  } // ctor

  public RslpSt (String _agwId, String _rackId, String _shelfId, String _slotId, String _cardId, String _portId)
  {
    agwId = _agwId;
    rackId = _rackId;
    shelfId = _shelfId;
    slotId = _slotId;
    cardId = _cardId;
    portId = _portId;
  } // ctor

} // class RslpSt
