package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/StatusSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public final class StatusSt implements org.omg.CORBA.portable.IDLEntity
{
  public KTCosNMS.xAGWPackage.UsageStateEnum usageStatus = null;
  public KTCosNMS.xAGWPackage.OperStatusEnum operStatus = null;
  public KTCosNMS.xAGWPackage.EquipStatusEnum equipStatus = null;
  public KTCosNMS.xAGWPackage.AdminStatusEnum adminStatus = null;
  public String alarmStatus = null;
  public KTCosNMS.xAGWPackage.LoopBackStatusEnum loopBackStatus = null;
  public KTCosNMS.xAGWPackage.ModeStatusEnum protectionStatus = null;
  public String swVersion = null;
  public String hwVersion = null;
  public String fwVersion = null;
  public String failReason = null;

  public StatusSt ()
  {
  } // ctor

  public StatusSt (KTCosNMS.xAGWPackage.UsageStateEnum _usageStatus, KTCosNMS.xAGWPackage.OperStatusEnum _operStatus, KTCosNMS.xAGWPackage.EquipStatusEnum _equipStatus, KTCosNMS.xAGWPackage.AdminStatusEnum _adminStatus, String _alarmStatus, KTCosNMS.xAGWPackage.LoopBackStatusEnum _loopBackStatus, KTCosNMS.xAGWPackage.ModeStatusEnum _protectionStatus, String _swVersion, String _hwVersion, String _fwVersion, String _failReason)
  {
    usageStatus = _usageStatus;
    operStatus = _operStatus;
    equipStatus = _equipStatus;
    adminStatus = _adminStatus;
    alarmStatus = _alarmStatus;
    loopBackStatus = _loopBackStatus;
    protectionStatus = _protectionStatus;
    swVersion = _swVersion;
    hwVersion = _hwVersion;
    fwVersion = _fwVersion;
    failReason = _failReason;
  } // ctor

} // class StatusSt
