package KTCosNMS.xAGWPackage;


import lombok.ToString;
import org.omg.CORBA.Any;
import org.omg.CORBA.ORB;

import java.util.ArrayList;
import java.util.List;

/**
* KTCosNMS/xAGWPackage/StatEventSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/
@ToString
public final class StatEventSt implements org.omg.CORBA.portable.IDLEntity
{
  public String emsId = null;
  public String agwId = null;
  public String userId = null;
  public String password = null;
  public String fileLocation = null;
  public String fileSize = null;
  public String eventTime = null;

  public StatEventSt ()
  {
  } // ctor

  public StatEventSt (String _emsId, String _agwId, String _userId, String _password, String _fileLocation, String _fileSize, String _eventTime)
  {
    emsId = _emsId;
    agwId = _agwId;
    userId = _userId;
    password = _password;
    fileLocation = _fileLocation;
    fileSize = _fileSize;
    eventTime = _eventTime;
  } // ctor
  public StatEventSt setStatEventSt() {
    StatEventSt statEventSt = new StatEventSt();
    statEventSt.emsId = "GGSWNSA03";
    statEventSt.agwId = "";
    statEventSt.userId = "ipfm";
    statEventSt.password = "ipfm";
    statEventSt.eventTime = "2022-11-04 00:00:01";
    statEventSt.fileLocation = "/Backup/BCNNMS/BCNNMS_TRAFFIC_OUT_2022-11-01-23-45-00.xml";
    statEventSt.fileSize = "1047";

    return statEventSt;
  }

} // class StatEventSt
