package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwAlarmExtEventHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

abstract public class stKtAgwAlarmExtEventHelper
{
  private static String  _id = "IDL:KTCosNMS/xAGW/stKtAgwAlarmExtEvent:1.0";

  public static void insert (org.omg.CORBA.Any a, KTCosNMS.xAGWPackage.stKtAgwAlarmExtEvent that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static KTCosNMS.xAGWPackage.stKtAgwAlarmExtEvent extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [19];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[0] = new org.omg.CORBA.StructMember (
            "agwType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "agwId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "nativeAlarmCode",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_wstring_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "nativeDeviceName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "alarmId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[5] = new org.omg.CORBA.StructMember (
            "severity",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[6] = new org.omg.CORBA.StructMember (
            "correlationFlag",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[7] = new org.omg.CORBA.StructMember (
            "connectedEx",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[8] = new org.omg.CORBA.StructMember (
            "tid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[9] = new org.omg.CORBA.StructMember (
            "ssid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[10] = new org.omg.CORBA.StructMember (
            "oid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[11] = new org.omg.CORBA.StructMember (
            "rid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[12] = new org.omg.CORBA.StructMember (
            "sid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[13] = new org.omg.CORBA.StructMember (
            "cid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_short);
          _members0[14] = new org.omg.CORBA.StructMember (
            "lid",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[15] = new org.omg.CORBA.StructMember (
            "date",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[16] = new org.omg.CORBA.StructMember (
            "reserved1",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[17] = new org.omg.CORBA.StructMember (
            "reserved2",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[18] = new org.omg.CORBA.StructMember (
            "reserved3",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (KTCosNMS.xAGWPackage.stKtAgwAlarmExtEventHelper.id (), "stKtAgwAlarmExtEvent", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static KTCosNMS.xAGWPackage.stKtAgwAlarmExtEvent read (org.omg.CORBA.portable.InputStream istream)
  {
    KTCosNMS.xAGWPackage.stKtAgwAlarmExtEvent value = new KTCosNMS.xAGWPackage.stKtAgwAlarmExtEvent ();
    value.agwType = istream.read_short ();
    value.agwId = istream.read_string ();
    value.nativeAlarmCode = istream.read_string ();
    value.nativeDeviceName = istream.read_wstring ();
    value.alarmId = istream.read_long ();
    value.severity = istream.read_short ();
    value.correlationFlag = istream.read_short ();
    value.connectedEx = istream.read_string ();
    value.tid = istream.read_short ();
    value.ssid = istream.read_short ();
    value.oid = istream.read_short ();
    value.rid = istream.read_short ();
    value.sid = istream.read_short ();
    value.cid = istream.read_short ();
    value.lid = istream.read_short ();
    value.date = istream.read_string ();
    value.reserved1 = istream.read_string ();
    value.reserved2 = istream.read_string ();
    value.reserved3 = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, KTCosNMS.xAGWPackage.stKtAgwAlarmExtEvent value)
  {
    ostream.write_short (value.agwType);
    ostream.write_string (value.agwId);
    ostream.write_string (value.nativeAlarmCode);
    ostream.write_wstring (value.nativeDeviceName);
    ostream.write_long (value.alarmId);
    ostream.write_short (value.severity);
    ostream.write_short (value.correlationFlag);
    ostream.write_string (value.connectedEx);
    ostream.write_short (value.tid);
    ostream.write_short (value.ssid);
    ostream.write_short (value.oid);
    ostream.write_short (value.rid);
    ostream.write_short (value.sid);
    ostream.write_short (value.cid);
    ostream.write_short (value.lid);
    ostream.write_string (value.date);
    ostream.write_string (value.reserved1);
    ostream.write_string (value.reserved2);
    ostream.write_string (value.reserved3);
  }

}
