package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwSubSysConfReq.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class stKtAgwSubSysConfReq implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;

  public stKtAgwSubSysConfReq ()
  {
  } // ctor

  public stKtAgwSubSysConfReq (String _agwId)
  {
    agwId = _agwId;
  } // ctor

} // class stKtAgwSubSysConfReq
