package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwSubSysConfig4BcnNmsResp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class stKtAgwSubSysConfig4BcnNmsResp implements org.omg.CORBA.portable.IDLEntity
{
  public String sysId = null;

  // AGW System Id(M) : use KT's AGW Colcode
  public String sysName = null;

  // AGW Name(M): use Vendor specified system name
  public String subSysId = null;

  //  of Sub-system
  public String equipmentId = null;

  //  of Sub-system
  public String emsId = null;

  // EMS Id(M) : use KT's EMS Colcode
  public String officeId = null;

  // KT's brance office name for AGW sub-system(O)
  public String headquarterId = null;

  // KT's headquarter name for AGW sub-system(O)
  public String vendorName = null;

  // AGW vendor's name(O) : LG , SAMSUNG, LUCENT ...
  public String managementIpAddress = null;

  // AGW sub-system's Ip address(M) : if does not exist, use AGW's Ip address
  public String manufactureDate = null;

  // AGW's installed date in KT official site(O), (YYYY-MM-DD hh:mm:ss)
  public String serialNumber = null;

  // AGW's serial number(O)
  public String description = null;

  // AGW's additional information(O)
  public int usageState = (int)0;

  public stKtAgwSubSysConfig4BcnNmsResp ()
  {
  } // ctor

  public stKtAgwSubSysConfig4BcnNmsResp (String _sysId, String _sysName, String _subSysId, String _equipmentId, String _emsId, String _officeId, String _headquarterId, String _vendorName, String _managementIpAddress, String _manufactureDate, String _serialNumber, String _description, int _usageState)
  {
    sysId = _sysId;
    sysName = _sysName;
    subSysId = _subSysId;
    equipmentId = _equipmentId;
    emsId = _emsId;
    officeId = _officeId;
    headquarterId = _headquarterId;
    vendorName = _vendorName;
    managementIpAddress = _managementIpAddress;
    manufactureDate = _manufactureDate;
    serialNumber = _serialNumber;
    description = _description;
    usageState = _usageState;
  } // ctor

} // class stKtAgwSubSysConfig4BcnNmsResp
