package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwEMSRunStateEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class stKtAgwEMSRunStateEvent implements org.omg.CORBA.portable.IDLEntity
{
  public short agwEmsType = (short)0;

  // Access Gateway Type
  public String agwEmsId = null;

  // Access Gateway Id
  public short emsState = (short)0;

  // EMS Running State : enSystemState
  public String date = null;

  public stKtAgwEMSRunStateEvent ()
  {
  } // ctor

  public stKtAgwEMSRunStateEvent (short _agwEmsType, String _agwEmsId, short _emsState, String _date)
  {
    agwEmsType = _agwEmsType;
    agwEmsId = _agwEmsId;
    emsState = _emsState;
    date = _date;
  } // ctor

} // class stKtAgwEMSRunStateEvent
