package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwSetEventFilter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class stKtAgwSetEventFilter implements org.omg.CORBA.portable.IDLEntity
{
  public short agwType = (short)0;

  // Access Gateway Type
  public String agwId = null;

  // Access Gateway Id
  public short msgType = (short)0;

  // T?? Type
  public int opCode = (int)0;

  // 0: t? ? MsgType
  public short setFlag = (short)0;

  public stKtAgwSetEventFilter ()
  {
  } // ctor

  public stKtAgwSetEventFilter (short _agwType, String _agwId, short _msgType, int _opCode, short _setFlag)
  {
    agwType = _agwType;
    agwId = _agwId;
    msgType = _msgType;
    opCode = _opCode;
    setFlag = _setFlag;
  } // ctor

} // class stKtAgwSetEventFilter
