package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwEMSCpuStateEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class stKtAgwEMSCpuStateEvent implements org.omg.CORBA.portable.IDLEntity
{
  public short agwEmsType = (short)0;

  // Access Gateway EMS Type
  public String agwEmsId = null;

  // Access Gateway EMS Id
  public short idlePercent = (short)0;

  // Idle Percent ( % )
  public short usrPercent = (short)0;

  // User Used Percent ( % )
  public short sysPercent = (short)0;

  // Kernel Used Percent ( % )
  public short ioWaitPercent = (short)0;

  // IOWait Used Percent ( % )
  public short swapPercent = (short)0;

  // Swap Used Percent ( % )
  public String date = null;

  public stKtAgwEMSCpuStateEvent ()
  {
  } // ctor

  public stKtAgwEMSCpuStateEvent (short _agwEmsType, String _agwEmsId, short _idlePercent, short _usrPercent, short _sysPercent, short _ioWaitPercent, short _swapPercent, String _date)
  {
    agwEmsType = _agwEmsType;
    agwEmsId = _agwEmsId;
    idlePercent = _idlePercent;
    usrPercent = _usrPercent;
    sysPercent = _sysPercent;
    ioWaitPercent = _ioWaitPercent;
    swapPercent = _swapPercent;
    date = _date;
  } // ctor

} // class stKtAgwEMSCpuStateEvent
