package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwEocmsManagedAgwInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class stKtAgwEocmsManagedAgwInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String eocmsId = null;

  // EOCMS Id
  public String agwIdSeq[] = null;

  public stKtAgwEocmsManagedAgwInfo ()
  {
  } // ctor

  public stKtAgwEocmsManagedAgwInfo (String _eocmsId, String[] _agwIdSeq)
  {
    eocmsId = _eocmsId;
    agwIdSeq = _agwIdSeq;
  } // ctor

} // class stKtAgwEocmsManagedAgwInfo
