package KTCosNMS.xAGWPackage;


import lombok.ToString;
import org.omg.CORBA.Any;
import org.omg.CORBA.ORB;

import java.util.ArrayList;
import java.util.List;

/**
* KTCosNMS/xAGWPackage/stKtAgwAlarmHistoryReq.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/
@ToString
public final class stKtAgwAlarmHistoryReq implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;

  // Access Gateway Id
  public String fromDate = null;

  // Start Date(YYYY-MM-DD hh:mm:ss)
  public String toDate = null;

  public stKtAgwAlarmHistoryReq ()
  {
  } // ctor

  public stKtAgwAlarmHistoryReq (String _agwId, String _fromDate, String _toDate)
  {
    agwId = _agwId;
    fromDate = _fromDate;
    toDate = _toDate;
  } // ctor
  public stKtAgwAlarmHistoryReq setStKtAgwAlarmHistoryReq() {
    stKtAgwAlarmHistoryReq stKtAgwAlarmHistoryReq = new stKtAgwAlarmHistoryReq();
    stKtAgwAlarmHistoryReq.agwId = "JNHS02588";
    stKtAgwAlarmHistoryReq.fromDate = "2022-11-04 23:59:59";
    stKtAgwAlarmHistoryReq.toDate = "2022-11-04 23:59:59";
    return stKtAgwAlarmHistoryReq;
  }



} // class stKtAgwAlarmHistoryReq
