package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/stKtAgwSubSysConfig4BcnNmsRespHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class stKtAgwSubSysConfig4BcnNmsRespHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.stKtAgwSubSysConfig4BcnNmsResp value = null;

  public stKtAgwSubSysConfig4BcnNmsRespHolder ()
  {
  }

  public stKtAgwSubSysConfig4BcnNmsRespHolder (KTCosNMS.xAGWPackage.stKtAgwSubSysConfig4BcnNmsResp initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.stKtAgwSubSysConfig4BcnNmsRespHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.stKtAgwSubSysConfig4BcnNmsRespHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.stKtAgwSubSysConfig4BcnNmsRespHelper.type ();
  }

}
