package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwEMSProcStateEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class stKtAgwEMSProcStateEvent implements org.omg.CORBA.portable.IDLEntity
{
  public short agwEmsType = (short)0;

  // Access Gateway EMS Type
  public String agwEmsId = null;

  // Access Gateway EMS Id
  public String procName = null;

  // Process Name
  public int procId = (int)0;

  // Process Id
  public int pprocId = (int)0;

  // Parent Process Id
  public String procState = null;

  // Process State
  public String procStartTime = null;

  // Process Start Time(YYYY-MM-DD hh:mm:ss)
  public int procTotalSize = (int)0;

  // Process Total Size
  public int procResSize = (int)0;

  // Process Resident Size
  public String procCpuUsage = null;

  // Process CPU Usage( ???)
  public String procCpuWeight = null;

  // Process CPU Weight ( ? ?? % )
  public String date = null;

  public stKtAgwEMSProcStateEvent ()
  {
  } // ctor

  public stKtAgwEMSProcStateEvent (short _agwEmsType, String _agwEmsId, String _procName, int _procId, int _pprocId, String _procState, String _procStartTime, int _procTotalSize, int _procResSize, String _procCpuUsage, String _procCpuWeight, String _date)
  {
    agwEmsType = _agwEmsType;
    agwEmsId = _agwEmsId;
    procName = _procName;
    procId = _procId;
    pprocId = _pprocId;
    procState = _procState;
    procStartTime = _procStartTime;
    procTotalSize = _procTotalSize;
    procResSize = _procResSize;
    procCpuUsage = _procCpuUsage;
    procCpuWeight = _procCpuWeight;
    date = _date;
  } // ctor

} // class stKtAgwEMSProcStateEvent
