package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwPerfDumping4BcnNmsEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class stKtAgwPerfDumping4BcnNmsEvent implements org.omg.CORBA.portable.IDLEntity
{
  public String emsId = null;

  // EMS Id(M) : use KT's EMS Colcode
  public String sysId = null;

  // AGW System Id(M) : use KT's AGW Colcode
  public String fileLocation = null;

  // Performance & statistics stored file name(full path, including filename)
  public String repTime = null;

  public stKtAgwPerfDumping4BcnNmsEvent ()
  {
  } // ctor

  public stKtAgwPerfDumping4BcnNmsEvent (String _emsId, String _sysId, String _fileLocation, String _repTime)
  {
    emsId = _emsId;
    sysId = _sysId;
    fileLocation = _fileLocation;
    repTime = _repTime;
  } // ctor

} // class stKtAgwPerfDumping4BcnNmsEvent
