package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwAlarmHistoryReq.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class stKtAgwAlarmHistoryReq implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;

  // Access Gateway Id
  public String fromDate = null;

  // Start Date(YYYY-MM-DD hh:mm:ss)
  public String toDate = null;

  public stKtAgwAlarmHistoryReq ()
  {
  } // ctor

  public stKtAgwAlarmHistoryReq (String _agwId, String _fromDate, String _toDate)
  {
    agwId = _agwId;
    fromDate = _fromDate;
    toDate = _toDate;
  } // ctor

} // class stKtAgwAlarmHistoryReq
