package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwSysConfResp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class stKtAgwSysConfResp implements org.omg.CORBA.portable.IDLEntity
{
  public short agwType = (short)0;

  // Access Gateway Type
  public String agwId = null;

  // Access Gateway Id
  public String connectedEx = null;

  //  PX0X Truman Code
  public String date = null;

  public stKtAgwSysConfResp ()
  {
  } // ctor

  public stKtAgwSysConfResp (short _agwType, String _agwId, String _connectedEx, String _date)
  {
    agwType = _agwType;
    agwId = _agwId;
    connectedEx = _connectedEx;
    date = _date;
  } // ctor

} // class stKtAgwSysConfResp
