package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwEMSDbStateEvent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class stKtAgwEMSDbStateEvent implements org.omg.CORBA.portable.IDLEntity
{
  public short agwEmsType = (short)0;

  // Access Gateway EMS Type
  public String agwEmsId = null;

  // Access Gateway EMS Id
  public float totalSize = (float)0;

  // Total Size ( Kbytes )
  public float usedSize = (float)0;

  // Used Size ( Kbytes )
  public float freeSize = (float)0;

  // Free Size ( Kbytes )
  public float usedPercent = (float)0;

  // Used Percent ( % )
  public String date = null;

  public stKtAgwEMSDbStateEvent ()
  {
  } // ctor

  public stKtAgwEMSDbStateEvent (short _agwEmsType, String _agwEmsId, float _totalSize, float _usedSize, float _freeSize, float _usedPercent, String _date)
  {
    agwEmsType = _agwEmsType;
    agwEmsId = _agwEmsId;
    totalSize = _totalSize;
    usedSize = _usedSize;
    freeSize = _freeSize;
    usedPercent = _usedPercent;
    date = _date;
  } // ctor

} // class stKtAgwEMSDbStateEvent
