package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwSubSysConfResp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class stKtAgwSubSysConfResp implements org.omg.CORBA.portable.IDLEntity
{
  public short agwType = (short)0;

  // Access Gateway Type
  public String agwId = null;

  // Access Gateway Id
  public String connectedEx = null;

  // `?`?`? `?X`?`? Truman Code
  public short ssid = (short)0;

  // AGW `?`? `?`??`?`? Id
  public String date = null;

  public stKtAgwSubSysConfResp ()
  {
  } // ctor

  public stKtAgwSubSysConfResp (short _agwType, String _agwId, String _connectedEx, short _ssid, String _date)
  {
    agwType = _agwType;
    agwId = _agwId;
    connectedEx = _connectedEx;
    ssid = _ssid;
    date = _date;
  } // ctor

} // class stKtAgwSubSysConfResp
