package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwGetEventFilterResp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class stKtAgwGetEventFilterResp implements org.omg.CORBA.portable.IDLEntity
{
  public short agwType = (short)0;

  // Access Gateway Type
  public String agwId = null;

  // Access Gateway Id
  public short msgType = (short)0;

  // `(?`? Type
  public int opCode = (int)0;

  // 0: ` `?`? MsgType
  public short setFlag = (short)0;

  public stKtAgwGetEventFilterResp ()
  {
  } // ctor

  public stKtAgwGetEventFilterResp (short _agwType, String _agwId, short _msgType, int _opCode, short _setFlag)
  {
    agwType = _agwType;
    agwId = _agwId;
    msgType = _msgType;
    opCode = _opCode;
    setFlag = _setFlag;
  } // ctor

} // class stKtAgwGetEventFilterResp
