package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/stKtAgwGetEventFilterReq.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class stKtAgwGetEventFilterReq implements org.omg.CORBA.portable.IDLEntity
{
  public short agwType = (short)0;

  // Access Gateway Type
  public String agwId = null;

  public stKtAgwGetEventFilterReq ()
  {
  } // ctor

  public stKtAgwGetEventFilterReq (short _agwType, String _agwId)
  {
    agwType = _agwType;
    agwId = _agwId;
  } // ctor

} // class stKtAgwGetEventFilterReq
