package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/StorageTypeEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public class StorageTypeEnum implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 10;
  private static KTCosNMS.xAGWPackage.StorageTypeEnum[] __array = new KTCosNMS.xAGWPackage.StorageTypeEnum [__size];

  public static final int _UNKNOWN_STORAGETYPE = 0;
  public static final KTCosNMS.xAGWPackage.StorageTypeEnum UNKNOWN_STORAGETYPE = new KTCosNMS.xAGWPackage.StorageTypeEnum(_UNKNOWN_STORAGETYPE);
  public static final int _OTHER_STORAGETYPE = 1;
  public static final KTCosNMS.xAGWPackage.StorageTypeEnum OTHER_STORAGETYPE = new KTCosNMS.xAGWPackage.StorageTypeEnum(_OTHER_STORAGETYPE);
  public static final int _RAM_STORAGETYPE = 2;
  public static final KTCosNMS.xAGWPackage.StorageTypeEnum RAM_STORAGETYPE = new KTCosNMS.xAGWPackage.StorageTypeEnum(_RAM_STORAGETYPE);
  public static final int _VIRTUALMEMORY_STORAGETYPE = 3;
  public static final KTCosNMS.xAGWPackage.StorageTypeEnum VIRTUALMEMORY_STORAGETYPE = new KTCosNMS.xAGWPackage.StorageTypeEnum(_VIRTUALMEMORY_STORAGETYPE);
  public static final int _FIXEDDISK_STORAGETYPE = 4;
  public static final KTCosNMS.xAGWPackage.StorageTypeEnum FIXEDDISK_STORAGETYPE = new KTCosNMS.xAGWPackage.StorageTypeEnum(_FIXEDDISK_STORAGETYPE);
  public static final int _REMOVEABLEDISK_STORAGETYPE = 5;
  public static final KTCosNMS.xAGWPackage.StorageTypeEnum REMOVEABLEDISK_STORAGETYPE = new KTCosNMS.xAGWPackage.StorageTypeEnum(_REMOVEABLEDISK_STORAGETYPE);
  public static final int _FLOPPYDISK_STORAGETYPE = 6;
  public static final KTCosNMS.xAGWPackage.StorageTypeEnum FLOPPYDISK_STORAGETYPE = new KTCosNMS.xAGWPackage.StorageTypeEnum(_FLOPPYDISK_STORAGETYPE);
  public static final int _COMPACTDISC_STORAGETYPE = 7;
  public static final KTCosNMS.xAGWPackage.StorageTypeEnum COMPACTDISC_STORAGETYPE = new KTCosNMS.xAGWPackage.StorageTypeEnum(_COMPACTDISC_STORAGETYPE);
  public static final int _RAMDISK_STORAGETYPE = 8;
  public static final KTCosNMS.xAGWPackage.StorageTypeEnum RAMDISK_STORAGETYPE = new KTCosNMS.xAGWPackage.StorageTypeEnum(_RAMDISK_STORAGETYPE);
  public static final int _FLASH_STORAGETYPE = 9;
  public static final KTCosNMS.xAGWPackage.StorageTypeEnum FLASH_STORAGETYPE = new KTCosNMS.xAGWPackage.StorageTypeEnum(_FLASH_STORAGETYPE);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.xAGWPackage.StorageTypeEnum from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected StorageTypeEnum (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class StorageTypeEnum
