package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/StringSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public final class StringSt implements org.omg.CORBA.portable.IDLEntity
{
  public String str = null;

  public StringSt ()
  {
  } // ctor

  public StringSt (String _str)
  {
    str = _str;
  } // ctor

} // class StringSt
