package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/StringSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class StringSt implements org.omg.CORBA.portable.IDLEntity
{
  public String str = null;

  public StringSt ()
  {
  } // ctor

  public StringSt (String _str)
  {
    str = _str;
  } // ctor

} // class StringSt
