package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/TdxAgwInfoSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class TdxAgwInfoSt implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;
  public String agwName = null;
  public String equipmentId = null;
  public String L3Info = null;
  public String emsId = null;
  public String managementIpAddress = null;
  public String swVersion = null;
  public String hwVersion = null;
  public String swUpdate = null;
  public String hwUpdate = null;
  public KTCosNMS.xAGWPackage.UsageStateEnum usageState = null;
  public KTCosNMS.xAGWPackage.CommonOptSt varCommonOptSt = null;

  public TdxAgwInfoSt ()
  {
  } // ctor

  public TdxAgwInfoSt (String _agwId, String _agwName, String _equipmentId, String _L3Info, String _emsId, String _managementIpAddress, String _swVersion, String _hwVersion, String _swUpdate, String _hwUpdate, KTCosNMS.xAGWPackage.UsageStateEnum _usageState, KTCosNMS.xAGWPackage.CommonOptSt _varCommonOptSt)
  {
    agwId = _agwId;
    agwName = _agwName;
    equipmentId = _equipmentId;
    L3Info = _L3Info;
    emsId = _emsId;
    managementIpAddress = _managementIpAddress;
    swVersion = _swVersion;
    hwVersion = _hwVersion;
    swUpdate = _swUpdate;
    hwUpdate = _hwUpdate;
    usageState = _usageState;
    varCommonOptSt = _varCommonOptSt;
  } // ctor

} // class TdxAgwInfoSt
