package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/TdxAgwInfoStHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../../../src/main/resources/idl/KTCosNMS.idl
* 2022 12 11 Ͽ  6 10 50 KST
*/

public final class TdxAgwInfoStHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.TdxAgwInfoSt value = null;

  public TdxAgwInfoStHolder ()
  {
  }

  public TdxAgwInfoStHolder (KTCosNMS.xAGWPackage.TdxAgwInfoSt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.TdxAgwInfoStHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.TdxAgwInfoStHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.TdxAgwInfoStHelper.type ();
  }

}
