package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/TypeOfHolderEnum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public class TypeOfHolderEnum implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static KTCosNMS.xAGWPackage.TypeOfHolderEnum[] __array = new KTCosNMS.xAGWPackage.TypeOfHolderEnum [__size];

  public static final int _UNKNOWN_TYPEOFHOLDER = 0;
  public static final KTCosNMS.xAGWPackage.TypeOfHolderEnum UNKNOWN_TYPEOFHOLDER = new KTCosNMS.xAGWPackage.TypeOfHolderEnum(_UNKNOWN_TYPEOFHOLDER);
  public static final int _RACK_TYPEOFHOLDER = 1;
  public static final KTCosNMS.xAGWPackage.TypeOfHolderEnum RACK_TYPEOFHOLDER = new KTCosNMS.xAGWPackage.TypeOfHolderEnum(_RACK_TYPEOFHOLDER);
  public static final int _SHELF_TYPEOFHOLDER = 2;
  public static final KTCosNMS.xAGWPackage.TypeOfHolderEnum SHELF_TYPEOFHOLDER = new KTCosNMS.xAGWPackage.TypeOfHolderEnum(_SHELF_TYPEOFHOLDER);
  public static final int _SLOT_TYPEOFHOLDER = 3;
  public static final KTCosNMS.xAGWPackage.TypeOfHolderEnum SLOT_TYPEOFHOLDER = new KTCosNMS.xAGWPackage.TypeOfHolderEnum(_SLOT_TYPEOFHOLDER);

  public int value ()
  {
    return __value;
  }

  public static KTCosNMS.xAGWPackage.TypeOfHolderEnum from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TypeOfHolderEnum (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TypeOfHolderEnum
