package KTCosNMS.xAGWPackage;

/**
* KTCosNMS/xAGWPackage/TypeOfHolderEnumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
*/

public final class TypeOfHolderEnumHolder implements org.omg.CORBA.portable.Streamable
{
  public KTCosNMS.xAGWPackage.TypeOfHolderEnum value = null;

  public TypeOfHolderEnumHolder ()
  {
  }

  public TypeOfHolderEnumHolder (KTCosNMS.xAGWPackage.TypeOfHolderEnum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = KTCosNMS.xAGWPackage.TypeOfHolderEnumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    KTCosNMS.xAGWPackage.TypeOfHolderEnumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return KTCosNMS.xAGWPackage.TypeOfHolderEnumHelper.type ();
  }

}
