package KTCosNMS.xAGWPackage;


/**
* KTCosNMS/xAGWPackage/VopServiceIPSt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../corba_test/BcNNMS_AGW.idl
* 2022 10 19   6 39 28 KST
*/

public final class VopServiceIPSt implements org.omg.CORBA.portable.IDLEntity
{
  public String agwId = null;
  public String sswIP = null;
  public String agwIP = null;
  public String ipPurpose = null;

  //2007-08-03 `)? `?`?
  public String vLanId = null;

  public VopServiceIPSt ()
  {
  } // ctor

  public VopServiceIPSt (String _agwId, String _sswIP, String _agwIP, String _ipPurpose, String _vLanId)
  {
    agwId = _agwId;
    sswIP = _sswIP;
    agwIP = _agwIP;
    ipPurpose = _ipPurpose;
    vLanId = _vLanId;
  } // ctor

} // class VopServiceIPSt
